[tool.poetry]
name = "imperial-dateutil"
version = "0.1.3"
description = "Utility for imperial dating system that supports both era indomitus system and original system"
authors = ["Seonghyeon Kim <kim@seonghyeon.dev>"]
license = "GPL-3.0-only"
readme = "README.md"
repository = "https://github.com/NovemberOscar/imperial-dateutil"
keywords = ["sanic", "jwt", "json web token"]
classifiers=[
        'License :: OSI Approved :: GNU General Public License v3 (GPLv3)',
        "Operating System :: OS Independent",
        'Programming Language :: Python :: 3.5',
        'Programming Language :: Python :: 3.6',
        'Programming Language :: Python :: 3.7',
        'Programming Language :: Python :: 3.8',
        'Environment :: Console',
    ]

[tool.poetry.dependencies]
python = "^3.5"

[tool.poetry.dev-dependencies]
pytest = "*"
sphinx = "^2.3"
sphinx_rtd_theme = "^0.4.3"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
