[tool.poetry]
name = "django-redis-sentinel-plugin"
version = "1.0.0"
description = "django-redis plugin that supports Sentinel Cluster HA"
authors = ["banxi1988 <banxi1988@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.6"
django-redis = "^4.10.0"
redis = "^3.3.11"
django = "^2.2.6"

[tool.poetry.dev-dependencies]
msgpack-python = "^0.5.6"
pytest = "^5.2.1"
hiredis = "1.0.1"
pytest-django = "^3.6.0"
fakeredis = "^1.1.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
