# Generated by Django 2.2 on 2019-06-23 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0005_auto_20190617_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetcategories',
            name='category_type',
            field=models.CharField(choices=[('Annual', 'Annual'), ('Monthly', 'Monthly')], max_length=7, verbose_name='category Type'),
        ),
    ]
