
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

from __future__ import absolute_import
import json

version_json = '''
{
 "date": "2019-12-20T18:07:20+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "74a7e7d8c9211eb3789460c4b49b54c150edb11b",
 "version": "2019.12.20"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
