{
 "title": "MDH Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Running instances",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "first",
   "targets": [
    { "expr": "docker_n_containers_running" }
   ]
  },
  {
   "title": "Stoped instances",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "docker_n_containers_stopped" }
   ]
  },
  {
   "title": "CPU Usage %",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "docker_container_cpu_usage_percent",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "HTTP Request",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(mdh_gunicorn_http_request_rate_per_second[5m])",
     "legendFormat": "{{worker}}"
    }
   ]
  },
  {
   "title": "Mem used %",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "docker_container_mem_usage_percent",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "Traffic",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(docker_container_net_tx_bytes[5m])",
     "legendFormat": "{{container_name}} TX bytes"
    },
    {
     "expr": "rate(docker_container_net_rx_bytes[5m])",
     "legendFormat": "{{container_name}} RX bytes"
    }
   ]
  },
  {
   "title": "Disk IO",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(docker_container_blkio_io_service_bytes_recursive_read[5m])",
     "legendFormat": "{{container_name}}  Read"
    },
    {
     "expr": "rate(docker_container_blkio_io_service_bytes_recursive_write[5m])",
     "legendFormat": "{{container_name}}  Write"
    }
   ]
  }
 ]
}