[tool.poetry]
name = "bareasgi"
version = "3.5.1"
description = "A lightweight ASGI framework"
authors = ["Rob Blackbourn <rob.blackbourn@gmail.com>"]
license = "Apache-2.0"
readme = "README.md"
packages = [
    { include = "bareasgi" }
]
repository = "https://github.com/rob-blackbourn/bareasgi"

[tool.poetry.dependencies]
python = "^3.7"
baretypes = "^3.1"
bareutils = "^3.2"

[tool.poetry.dev-dependencies]
pytest = "^5.0"
pytest-asyncio = "^0.10"
pytest-runner = "^5.1"
uvicorn = "^0.9"
hypercorn = "^0.9"
Sphinx = "^1.8"
sphinxcontrib-websupport = "^1.1"
uvloop = "^0.13.0"
pylint = "^2.4"
mypy = "^0.740.0"
rope = "^0.14.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
