#AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"info": "01_demo.ipynb",
         "corr": "01_demo.ipynb",
         "fit_transform": "01_demo.ipynb"}

modules = ["model.py"]

git_url = "https://github.com/JiaxiangBU/item_based_recommender/tree/master/"

def custom_doc_links(name): return None