# coding: utf-8

"""
    Octopus Server API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2019.6.7+Branch.tags-2019.6.7.Sha.aa18dc6809953218c66f57eff7d26481d9b23d6a
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class ActionUpdateRemovedPackageUsage(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'package_reference': 'str',
        'used_by': 'str',
        'used_by_id': 'str',
        'used_by_name': 'str'
    }

    attribute_map = {
        'package_reference': 'PackageReference',
        'used_by': 'UsedBy',
        'used_by_id': 'UsedById',
        'used_by_name': 'UsedByName'
    }

    def __init__(self, package_reference=None, used_by=None, used_by_id=None, used_by_name=None):  # noqa: E501
        """ActionUpdateRemovedPackageUsage - a model defined in Swagger"""  # noqa: E501

        self._package_reference = None
        self._used_by = None
        self._used_by_id = None
        self._used_by_name = None
        self.discriminator = None

        if package_reference is not None:
            self.package_reference = package_reference
        if used_by is not None:
            self.used_by = used_by
        if used_by_id is not None:
            self.used_by_id = used_by_id
        if used_by_name is not None:
            self.used_by_name = used_by_name

    @property
    def package_reference(self):
        """Gets the package_reference of this ActionUpdateRemovedPackageUsage.  # noqa: E501


        :return: The package_reference of this ActionUpdateRemovedPackageUsage.  # noqa: E501
        :rtype: str
        """
        return self._package_reference

    @package_reference.setter
    def package_reference(self, package_reference):
        """Sets the package_reference of this ActionUpdateRemovedPackageUsage.


        :param package_reference: The package_reference of this ActionUpdateRemovedPackageUsage.  # noqa: E501
        :type: str
        """

        self._package_reference = package_reference

    @property
    def used_by(self):
        """Gets the used_by of this ActionUpdateRemovedPackageUsage.  # noqa: E501


        :return: The used_by of this ActionUpdateRemovedPackageUsage.  # noqa: E501
        :rtype: str
        """
        return self._used_by

    @used_by.setter
    def used_by(self, used_by):
        """Sets the used_by of this ActionUpdateRemovedPackageUsage.


        :param used_by: The used_by of this ActionUpdateRemovedPackageUsage.  # noqa: E501
        :type: str
        """
        allowed_values = ["ProjectVersionStrategy", "ProjectReleaseCreationStrategy", "ChannelRule"]  # noqa: E501
        if used_by not in allowed_values:
            raise ValueError(
                "Invalid value for `used_by` ({0}), must be one of {1}"  # noqa: E501
                .format(used_by, allowed_values)
            )

        self._used_by = used_by

    @property
    def used_by_id(self):
        """Gets the used_by_id of this ActionUpdateRemovedPackageUsage.  # noqa: E501


        :return: The used_by_id of this ActionUpdateRemovedPackageUsage.  # noqa: E501
        :rtype: str
        """
        return self._used_by_id

    @used_by_id.setter
    def used_by_id(self, used_by_id):
        """Sets the used_by_id of this ActionUpdateRemovedPackageUsage.


        :param used_by_id: The used_by_id of this ActionUpdateRemovedPackageUsage.  # noqa: E501
        :type: str
        """

        self._used_by_id = used_by_id

    @property
    def used_by_name(self):
        """Gets the used_by_name of this ActionUpdateRemovedPackageUsage.  # noqa: E501


        :return: The used_by_name of this ActionUpdateRemovedPackageUsage.  # noqa: E501
        :rtype: str
        """
        return self._used_by_name

    @used_by_name.setter
    def used_by_name(self, used_by_name):
        """Sets the used_by_name of this ActionUpdateRemovedPackageUsage.


        :param used_by_name: The used_by_name of this ActionUpdateRemovedPackageUsage.  # noqa: E501
        :type: str
        """

        self._used_by_name = used_by_name

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ActionUpdateRemovedPackageUsage, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ActionUpdateRemovedPackageUsage):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
