# coding: utf-8

"""
    Octopus Server API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2019.6.7+Branch.tags-2019.6.7.Sha.aa18dc6809953218c66f57eff7d26481d9b23d6a
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from octopus_deploy_swagger_client.models.library_variable_set_project_usage import LibraryVariableSetProjectUsage  # noqa: F401,E501


class LibraryVariableSetUsageResource(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'projects': 'list[LibraryVariableSetProjectUsage]',
        'count_of_projects_user_cannot_see': 'int',
        'count_of_releases_user_cannot_see': 'int',
        'last_modified_on': 'datetime',
        'last_modified_by': 'str',
        'links': 'dict(str, str)'
    }

    attribute_map = {
        'id': 'Id',
        'projects': 'Projects',
        'count_of_projects_user_cannot_see': 'CountOfProjectsUserCannotSee',
        'count_of_releases_user_cannot_see': 'CountOfReleasesUserCannotSee',
        'last_modified_on': 'LastModifiedOn',
        'last_modified_by': 'LastModifiedBy',
        'links': 'Links'
    }

    def __init__(self, id=None, projects=None, count_of_projects_user_cannot_see=None, count_of_releases_user_cannot_see=None, last_modified_on=None, last_modified_by=None, links=None):  # noqa: E501
        """LibraryVariableSetUsageResource - a model defined in Swagger"""  # noqa: E501

        self._id = None
        self._projects = None
        self._count_of_projects_user_cannot_see = None
        self._count_of_releases_user_cannot_see = None
        self._last_modified_on = None
        self._last_modified_by = None
        self._links = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if projects is not None:
            self.projects = projects
        if count_of_projects_user_cannot_see is not None:
            self.count_of_projects_user_cannot_see = count_of_projects_user_cannot_see
        if count_of_releases_user_cannot_see is not None:
            self.count_of_releases_user_cannot_see = count_of_releases_user_cannot_see
        if last_modified_on is not None:
            self.last_modified_on = last_modified_on
        if last_modified_by is not None:
            self.last_modified_by = last_modified_by
        if links is not None:
            self.links = links

    @property
    def id(self):
        """Gets the id of this LibraryVariableSetUsageResource.  # noqa: E501


        :return: The id of this LibraryVariableSetUsageResource.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this LibraryVariableSetUsageResource.


        :param id: The id of this LibraryVariableSetUsageResource.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def projects(self):
        """Gets the projects of this LibraryVariableSetUsageResource.  # noqa: E501


        :return: The projects of this LibraryVariableSetUsageResource.  # noqa: E501
        :rtype: list[LibraryVariableSetProjectUsage]
        """
        return self._projects

    @projects.setter
    def projects(self, projects):
        """Sets the projects of this LibraryVariableSetUsageResource.


        :param projects: The projects of this LibraryVariableSetUsageResource.  # noqa: E501
        :type: list[LibraryVariableSetProjectUsage]
        """

        self._projects = projects

    @property
    def count_of_projects_user_cannot_see(self):
        """Gets the count_of_projects_user_cannot_see of this LibraryVariableSetUsageResource.  # noqa: E501


        :return: The count_of_projects_user_cannot_see of this LibraryVariableSetUsageResource.  # noqa: E501
        :rtype: int
        """
        return self._count_of_projects_user_cannot_see

    @count_of_projects_user_cannot_see.setter
    def count_of_projects_user_cannot_see(self, count_of_projects_user_cannot_see):
        """Sets the count_of_projects_user_cannot_see of this LibraryVariableSetUsageResource.


        :param count_of_projects_user_cannot_see: The count_of_projects_user_cannot_see of this LibraryVariableSetUsageResource.  # noqa: E501
        :type: int
        """

        self._count_of_projects_user_cannot_see = count_of_projects_user_cannot_see

    @property
    def count_of_releases_user_cannot_see(self):
        """Gets the count_of_releases_user_cannot_see of this LibraryVariableSetUsageResource.  # noqa: E501


        :return: The count_of_releases_user_cannot_see of this LibraryVariableSetUsageResource.  # noqa: E501
        :rtype: int
        """
        return self._count_of_releases_user_cannot_see

    @count_of_releases_user_cannot_see.setter
    def count_of_releases_user_cannot_see(self, count_of_releases_user_cannot_see):
        """Sets the count_of_releases_user_cannot_see of this LibraryVariableSetUsageResource.


        :param count_of_releases_user_cannot_see: The count_of_releases_user_cannot_see of this LibraryVariableSetUsageResource.  # noqa: E501
        :type: int
        """

        self._count_of_releases_user_cannot_see = count_of_releases_user_cannot_see

    @property
    def last_modified_on(self):
        """Gets the last_modified_on of this LibraryVariableSetUsageResource.  # noqa: E501


        :return: The last_modified_on of this LibraryVariableSetUsageResource.  # noqa: E501
        :rtype: datetime
        """
        return self._last_modified_on

    @last_modified_on.setter
    def last_modified_on(self, last_modified_on):
        """Sets the last_modified_on of this LibraryVariableSetUsageResource.


        :param last_modified_on: The last_modified_on of this LibraryVariableSetUsageResource.  # noqa: E501
        :type: datetime
        """

        self._last_modified_on = last_modified_on

    @property
    def last_modified_by(self):
        """Gets the last_modified_by of this LibraryVariableSetUsageResource.  # noqa: E501


        :return: The last_modified_by of this LibraryVariableSetUsageResource.  # noqa: E501
        :rtype: str
        """
        return self._last_modified_by

    @last_modified_by.setter
    def last_modified_by(self, last_modified_by):
        """Sets the last_modified_by of this LibraryVariableSetUsageResource.


        :param last_modified_by: The last_modified_by of this LibraryVariableSetUsageResource.  # noqa: E501
        :type: str
        """

        self._last_modified_by = last_modified_by

    @property
    def links(self):
        """Gets the links of this LibraryVariableSetUsageResource.  # noqa: E501


        :return: The links of this LibraryVariableSetUsageResource.  # noqa: E501
        :rtype: dict(str, str)
        """
        return self._links

    @links.setter
    def links(self, links):
        """Sets the links of this LibraryVariableSetUsageResource.


        :param links: The links of this LibraryVariableSetUsageResource.  # noqa: E501
        :type: dict(str, str)
        """

        self._links = links

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(LibraryVariableSetUsageResource, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, LibraryVariableSetUsageResource):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
