# coding: utf-8

"""
    Octopus Server API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2019.6.7+Branch.tags-2019.6.7.Sha.aa18dc6809953218c66f57eff7d26481d9b23d6a
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class SpaceResource(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'name': 'str',
        'description': 'str',
        'is_default': 'bool',
        'task_queue_stopped': 'bool',
        'space_managers_teams': 'list[str]',
        'space_managers_team_members': 'list[str]',
        'last_modified_on': 'datetime',
        'last_modified_by': 'str',
        'links': 'dict(str, str)'
    }

    attribute_map = {
        'id': 'Id',
        'name': 'Name',
        'description': 'Description',
        'is_default': 'IsDefault',
        'task_queue_stopped': 'TaskQueueStopped',
        'space_managers_teams': 'SpaceManagersTeams',
        'space_managers_team_members': 'SpaceManagersTeamMembers',
        'last_modified_on': 'LastModifiedOn',
        'last_modified_by': 'LastModifiedBy',
        'links': 'Links'
    }

    def __init__(self, id=None, name=None, description=None, is_default=None, task_queue_stopped=None, space_managers_teams=None, space_managers_team_members=None, last_modified_on=None, last_modified_by=None, links=None):  # noqa: E501
        """SpaceResource - a model defined in Swagger"""  # noqa: E501

        self._id = None
        self._name = None
        self._description = None
        self._is_default = None
        self._task_queue_stopped = None
        self._space_managers_teams = None
        self._space_managers_team_members = None
        self._last_modified_on = None
        self._last_modified_by = None
        self._links = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if name is not None:
            self.name = name
        if description is not None:
            self.description = description
        if is_default is not None:
            self.is_default = is_default
        if task_queue_stopped is not None:
            self.task_queue_stopped = task_queue_stopped
        if space_managers_teams is not None:
            self.space_managers_teams = space_managers_teams
        if space_managers_team_members is not None:
            self.space_managers_team_members = space_managers_team_members
        if last_modified_on is not None:
            self.last_modified_on = last_modified_on
        if last_modified_by is not None:
            self.last_modified_by = last_modified_by
        if links is not None:
            self.links = links

    @property
    def id(self):
        """Gets the id of this SpaceResource.  # noqa: E501


        :return: The id of this SpaceResource.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this SpaceResource.


        :param id: The id of this SpaceResource.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this SpaceResource.  # noqa: E501


        :return: The name of this SpaceResource.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this SpaceResource.


        :param name: The name of this SpaceResource.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def description(self):
        """Gets the description of this SpaceResource.  # noqa: E501


        :return: The description of this SpaceResource.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this SpaceResource.


        :param description: The description of this SpaceResource.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def is_default(self):
        """Gets the is_default of this SpaceResource.  # noqa: E501


        :return: The is_default of this SpaceResource.  # noqa: E501
        :rtype: bool
        """
        return self._is_default

    @is_default.setter
    def is_default(self, is_default):
        """Sets the is_default of this SpaceResource.


        :param is_default: The is_default of this SpaceResource.  # noqa: E501
        :type: bool
        """

        self._is_default = is_default

    @property
    def task_queue_stopped(self):
        """Gets the task_queue_stopped of this SpaceResource.  # noqa: E501


        :return: The task_queue_stopped of this SpaceResource.  # noqa: E501
        :rtype: bool
        """
        return self._task_queue_stopped

    @task_queue_stopped.setter
    def task_queue_stopped(self, task_queue_stopped):
        """Sets the task_queue_stopped of this SpaceResource.


        :param task_queue_stopped: The task_queue_stopped of this SpaceResource.  # noqa: E501
        :type: bool
        """

        self._task_queue_stopped = task_queue_stopped

    @property
    def space_managers_teams(self):
        """Gets the space_managers_teams of this SpaceResource.  # noqa: E501


        :return: The space_managers_teams of this SpaceResource.  # noqa: E501
        :rtype: list[str]
        """
        return self._space_managers_teams

    @space_managers_teams.setter
    def space_managers_teams(self, space_managers_teams):
        """Sets the space_managers_teams of this SpaceResource.


        :param space_managers_teams: The space_managers_teams of this SpaceResource.  # noqa: E501
        :type: list[str]
        """

        self._space_managers_teams = space_managers_teams

    @property
    def space_managers_team_members(self):
        """Gets the space_managers_team_members of this SpaceResource.  # noqa: E501


        :return: The space_managers_team_members of this SpaceResource.  # noqa: E501
        :rtype: list[str]
        """
        return self._space_managers_team_members

    @space_managers_team_members.setter
    def space_managers_team_members(self, space_managers_team_members):
        """Sets the space_managers_team_members of this SpaceResource.


        :param space_managers_team_members: The space_managers_team_members of this SpaceResource.  # noqa: E501
        :type: list[str]
        """

        self._space_managers_team_members = space_managers_team_members

    @property
    def last_modified_on(self):
        """Gets the last_modified_on of this SpaceResource.  # noqa: E501


        :return: The last_modified_on of this SpaceResource.  # noqa: E501
        :rtype: datetime
        """
        return self._last_modified_on

    @last_modified_on.setter
    def last_modified_on(self, last_modified_on):
        """Sets the last_modified_on of this SpaceResource.


        :param last_modified_on: The last_modified_on of this SpaceResource.  # noqa: E501
        :type: datetime
        """

        self._last_modified_on = last_modified_on

    @property
    def last_modified_by(self):
        """Gets the last_modified_by of this SpaceResource.  # noqa: E501


        :return: The last_modified_by of this SpaceResource.  # noqa: E501
        :rtype: str
        """
        return self._last_modified_by

    @last_modified_by.setter
    def last_modified_by(self, last_modified_by):
        """Sets the last_modified_by of this SpaceResource.


        :param last_modified_by: The last_modified_by of this SpaceResource.  # noqa: E501
        :type: str
        """

        self._last_modified_by = last_modified_by

    @property
    def links(self):
        """Gets the links of this SpaceResource.  # noqa: E501


        :return: The links of this SpaceResource.  # noqa: E501
        :rtype: dict(str, str)
        """
        return self._links

    @links.setter
    def links(self, links):
        """Sets the links of this SpaceResource.


        :param links: The links of this SpaceResource.  # noqa: E501
        :type: dict(str, str)
        """

        self._links = links

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SpaceResource, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SpaceResource):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
