# coding: utf-8

"""
    Octopus Server API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2019.6.7+Branch.tags-2019.6.7.Sha.aa18dc6809953218c66f57eff7d26481d9b23d6a
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class StepUsageEntry(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'step_name': 'str',
        'step_id': 'str'
    }

    attribute_map = {
        'step_name': 'StepName',
        'step_id': 'StepId'
    }

    def __init__(self, step_name=None, step_id=None):  # noqa: E501
        """StepUsageEntry - a model defined in Swagger"""  # noqa: E501

        self._step_name = None
        self._step_id = None
        self.discriminator = None

        if step_name is not None:
            self.step_name = step_name
        if step_id is not None:
            self.step_id = step_id

    @property
    def step_name(self):
        """Gets the step_name of this StepUsageEntry.  # noqa: E501


        :return: The step_name of this StepUsageEntry.  # noqa: E501
        :rtype: str
        """
        return self._step_name

    @step_name.setter
    def step_name(self, step_name):
        """Sets the step_name of this StepUsageEntry.


        :param step_name: The step_name of this StepUsageEntry.  # noqa: E501
        :type: str
        """

        self._step_name = step_name

    @property
    def step_id(self):
        """Gets the step_id of this StepUsageEntry.  # noqa: E501


        :return: The step_id of this StepUsageEntry.  # noqa: E501
        :rtype: str
        """
        return self._step_id

    @step_id.setter
    def step_id(self, step_id):
        """Sets the step_id of this StepUsageEntry.


        :param step_id: The step_id of this StepUsageEntry.  # noqa: E501
        :type: str
        """

        self._step_id = step_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(StepUsageEntry, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, StepUsageEntry):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
