# coding: utf-8

"""
    Octopus Server API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2019.6.7+Branch.tags-2019.6.7.Sha.aa18dc6809953218c66f57eff7d26481d9b23d6a
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from octopus_deploy_swagger_client.models.library import Library  # noqa: F401,E501
from octopus_deploy_swagger_client.models.project import Project  # noqa: F401,E501


class TenantVariableResource(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'tenant_id': 'str',
        'tenant_name': 'str',
        'project_variables': 'dict(str, Project)',
        'library_variables': 'dict(str, Library)',
        'space_id': 'str',
        'last_modified_on': 'datetime',
        'last_modified_by': 'str',
        'links': 'dict(str, str)'
    }

    attribute_map = {
        'id': 'Id',
        'tenant_id': 'TenantId',
        'tenant_name': 'TenantName',
        'project_variables': 'ProjectVariables',
        'library_variables': 'LibraryVariables',
        'space_id': 'SpaceId',
        'last_modified_on': 'LastModifiedOn',
        'last_modified_by': 'LastModifiedBy',
        'links': 'Links'
    }

    def __init__(self, id=None, tenant_id=None, tenant_name=None, project_variables=None, library_variables=None, space_id=None, last_modified_on=None, last_modified_by=None, links=None):  # noqa: E501
        """TenantVariableResource - a model defined in Swagger"""  # noqa: E501

        self._id = None
        self._tenant_id = None
        self._tenant_name = None
        self._project_variables = None
        self._library_variables = None
        self._space_id = None
        self._last_modified_on = None
        self._last_modified_by = None
        self._links = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if tenant_id is not None:
            self.tenant_id = tenant_id
        if tenant_name is not None:
            self.tenant_name = tenant_name
        if project_variables is not None:
            self.project_variables = project_variables
        if library_variables is not None:
            self.library_variables = library_variables
        if space_id is not None:
            self.space_id = space_id
        if last_modified_on is not None:
            self.last_modified_on = last_modified_on
        if last_modified_by is not None:
            self.last_modified_by = last_modified_by
        if links is not None:
            self.links = links

    @property
    def id(self):
        """Gets the id of this TenantVariableResource.  # noqa: E501


        :return: The id of this TenantVariableResource.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this TenantVariableResource.


        :param id: The id of this TenantVariableResource.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def tenant_id(self):
        """Gets the tenant_id of this TenantVariableResource.  # noqa: E501


        :return: The tenant_id of this TenantVariableResource.  # noqa: E501
        :rtype: str
        """
        return self._tenant_id

    @tenant_id.setter
    def tenant_id(self, tenant_id):
        """Sets the tenant_id of this TenantVariableResource.


        :param tenant_id: The tenant_id of this TenantVariableResource.  # noqa: E501
        :type: str
        """

        self._tenant_id = tenant_id

    @property
    def tenant_name(self):
        """Gets the tenant_name of this TenantVariableResource.  # noqa: E501


        :return: The tenant_name of this TenantVariableResource.  # noqa: E501
        :rtype: str
        """
        return self._tenant_name

    @tenant_name.setter
    def tenant_name(self, tenant_name):
        """Sets the tenant_name of this TenantVariableResource.


        :param tenant_name: The tenant_name of this TenantVariableResource.  # noqa: E501
        :type: str
        """

        self._tenant_name = tenant_name

    @property
    def project_variables(self):
        """Gets the project_variables of this TenantVariableResource.  # noqa: E501


        :return: The project_variables of this TenantVariableResource.  # noqa: E501
        :rtype: dict(str, Project)
        """
        return self._project_variables

    @project_variables.setter
    def project_variables(self, project_variables):
        """Sets the project_variables of this TenantVariableResource.


        :param project_variables: The project_variables of this TenantVariableResource.  # noqa: E501
        :type: dict(str, Project)
        """

        self._project_variables = project_variables

    @property
    def library_variables(self):
        """Gets the library_variables of this TenantVariableResource.  # noqa: E501


        :return: The library_variables of this TenantVariableResource.  # noqa: E501
        :rtype: dict(str, Library)
        """
        return self._library_variables

    @library_variables.setter
    def library_variables(self, library_variables):
        """Sets the library_variables of this TenantVariableResource.


        :param library_variables: The library_variables of this TenantVariableResource.  # noqa: E501
        :type: dict(str, Library)
        """

        self._library_variables = library_variables

    @property
    def space_id(self):
        """Gets the space_id of this TenantVariableResource.  # noqa: E501


        :return: The space_id of this TenantVariableResource.  # noqa: E501
        :rtype: str
        """
        return self._space_id

    @space_id.setter
    def space_id(self, space_id):
        """Sets the space_id of this TenantVariableResource.


        :param space_id: The space_id of this TenantVariableResource.  # noqa: E501
        :type: str
        """

        self._space_id = space_id

    @property
    def last_modified_on(self):
        """Gets the last_modified_on of this TenantVariableResource.  # noqa: E501


        :return: The last_modified_on of this TenantVariableResource.  # noqa: E501
        :rtype: datetime
        """
        return self._last_modified_on

    @last_modified_on.setter
    def last_modified_on(self, last_modified_on):
        """Sets the last_modified_on of this TenantVariableResource.


        :param last_modified_on: The last_modified_on of this TenantVariableResource.  # noqa: E501
        :type: datetime
        """

        self._last_modified_on = last_modified_on

    @property
    def last_modified_by(self):
        """Gets the last_modified_by of this TenantVariableResource.  # noqa: E501


        :return: The last_modified_by of this TenantVariableResource.  # noqa: E501
        :rtype: str
        """
        return self._last_modified_by

    @last_modified_by.setter
    def last_modified_by(self, last_modified_by):
        """Sets the last_modified_by of this TenantVariableResource.


        :param last_modified_by: The last_modified_by of this TenantVariableResource.  # noqa: E501
        :type: str
        """

        self._last_modified_by = last_modified_by

    @property
    def links(self):
        """Gets the links of this TenantVariableResource.  # noqa: E501


        :return: The links of this TenantVariableResource.  # noqa: E501
        :rtype: dict(str, str)
        """
        return self._links

    @links.setter
    def links(self, links):
        """Sets the links of this TenantVariableResource.


        :param links: The links of this TenantVariableResource.  # noqa: E501
        :type: dict(str, str)
        """

        self._links = links

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(TenantVariableResource, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TenantVariableResource):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
