[tool.poetry]
name = "diff-pdf-visually"
version = "1.4.1"
description = "Quickly check whether there is a visible difference between two PDFs, using ImageMagick and pdftocairo."
authors = ["Bram Geron <bram@bram.xyz>"]
license = "MIT"
readme = "README.rst"
homepage = "https://github.com/bgeron/diff-pdf-visually"
repository = "https://github.com/bgeron/diff-pdf-visually"

[tool.poetry.dependencies]
python = "^3.0"

[tool.poetry.dev-dependencies]
pytest = "^3.0"
mypy = "*"

[tool.poetry.scripts]
diff-pdf-visually = 'diff_pdf_visually:__main__.main'
