[tool.poetry]
name = "toposim"
version = "0.1.0"
description = ""
authors = ["yajiez <yajiez.me@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
numpy = "^1.17.4"
pandas = "^0.25.3"
seaborn = "^0.9.0"
scikit-learn = "^0.22"
torch = "^1.3.1"
ipython = "^7.10.2"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
ipykernel = "^5.1.3"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
