from enum import Enum


class PaymentTypes(Enum):
    ADD_PAYMENT = 0
    ADD_PAYMENT_VALIDATE_CPF = 1
    ADD_PAYMENT_VALIDATE_CNPJ_FULL = 2
    ADD_PAYMENT_VALIDATE_CNPJ_ROOT = 3
    ADD_PAYMENT_PAY_SLIP = 4
    CHANGE_PAYMENT_PAY_SLIP = 512
    CHANGE_PAYMENT_VALUE = 517
    CHANGE_PAYMENT_DATE = 519
    REMOVE_PAYMENT_PAY_SLIP = 998
    REMOVE_PAYMENT = 999
