[tool.poetry]
name = "r2c_py_ast"
version = "0.1.0b1"
description = "Program analysis utilities for Python, by r2c. Used in [Bento](https://bento.dev)."
authors = ["R2C <hello@returntocorp.com>"]
homepage = "https://bento.dev"
packages = [
    { include = "r2c_py_ast" },
]
exclude = ["tests/**"]

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
