[tool.poetry]
name = "py-wave-runup"
version = "0.1.5"
description = "Empirical wave runup models implemented in Python"
authors = ["Chris Leaman"]
license = "GPL-3.0+"
readme = 'README.rst'
repository = 'https://github.com/chrisleaman/py-wave-runup'
homepage = 'https://github.com/chrisleaman/py-wave-runup'
documentation = 'https://py-wave-runup.readthedocs.io'

[tool.poetry.dependencies]
python = "^3.6 || ^3.7"
numpy = "^1.16"
black = {version = ">=18.3,<20.0", allows-prereleases = true}

[tool.poetry.dev-dependencies]
tox = "^3.13"
coverage = "^5.0"
pytest-runner = "^5.1"
pytest = "^5.3"
pre-commit = "^1.18"
codecov = "^2.0"
pytest-cov = "^2.8"
sphinx = "^2.3"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
