version: 2
jobs:
  build:
    working_directory: ~/scanapi
    docker:
      - image: circleci/python:3.7.3
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            python setup.py develop
            pip install -e .[dev] .[test]
      - run:
          name: Run tests
          command: ./venv/bin/pytest --cov=./scanapi --cov-report=xml
      - run:
          name: Upload coverage report to codecov.io
          command: ./venv/bin/codecov
