__logFile = None
__logEAFile = None
exchangeName = "binance"
appMode = "BACKTEST"        # "BACKTEST"; "TRADE"
_configs = None             # only for DEMO (Paper Trading)
_initForce = False          # only for DEMO (Paper Trading)
_ConfFile = None            # only for BACKTEST
# symbol = "BTC/USDT"
candleSize = "15m"      # 1m, 5m, 15m, 30m, 1h, 4h, 1d
# accountID = None
wssEndPoint = ""
apiKey = ""
apiSecret = ""
_axhline = None
settings = None