# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"ProxyManager": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://ecatkins.github.io/ProxyManager/"

git_url = "https://github.com/ecatkins/ProxyManager/tree/master/"

def custom_doc_links(name): return None
