columns:
    - [OBSERVATION_ID, observation_id, text]
    - [PRODUCT_ID, product_id, text]
    - [LINE_SAMPLES, samples, integer]
    - [IMAGE_LINES, lines, integer]
    - [IMAGE_CENTER_LATITUDE, center_latitude, real]
    - [IMAGE_CENTER_LONGITUDE, center_longitude, real]
    - [NORTH_AZIMUTH, north_azimuth, real]
    - [SCALED_PIXEL_WIDTH, pixel_width, real]
    - [VOLUME_ID, volume_id, text]
    - [FILE_NAME_SPECIFICATION, file_name_specification, text]
    - [PRODUCT_VERSION_ID, product_version_id, text]
    - [HICAL_VERSION, hical_version, text]
    - [TARGET_NAME, target_name, text]
    - [ORBIT_NUMBER, orbit_number, integer]
    - [MISSION_PHASE_NAME, mission_phase_name, text]
    - [RATIONALE_DESC, description, text]
    - [OBSERVATION_START_TIME, observation_start_time, timestamp]
    - [OBSERVATION_START_COUNT, observation_start_sclk, real]
    - [START_TIME, start_time, timestamp]
    - [STOP_TIME, stop_time, timestamp]
    - [SPACECRAFT_CLOCK_START_COUNT, sclk_start, real]
    - [SPACECRAFT_CLOCK_STOP_COUNT, sclk_stop, real]
    - [CCD_NAME, ccd_name, text]
    - [CHANNEL_NUMBER, channel_number, integer]
    - [FILTER_NAME, filter_name, text]
    - [SCAN_EXPOSURE_DURATION, scan_exposure_duration, real]
    - [DELTA_LINE_TIME_COUNT, delta_line_time_count, integer]
    - [BINNING, binning, integer]
    - [TDI, tdi, integer]
    - [TRIM_LINES, trim_lines, integer]
    - [FOCUS_POSITION_COUNT, focus_position_count, integer]
    - [FELICS_COMPRESSION_FLAG, felics_compression_flag, text]
    - [STIMULATION_LAMP_FLAG_RED, stimulation_lamp_flag_red, text]
    - [STIMULATION_LAMP_FLAG_BLUEGREEN, stimulation_lamp_flag_bluegreen, text]
    - [STIMULATION_LAMP_FLAG_NEARINFRARED, stimulation_lamp_flag_nearinfrared, text]
    - [LOOKUP_TABLE_TYPE, lookup_table_type, text]
    - [LOOKUP_TABLE_MINIMUM, lookup_table_minimum, integer]
    - [LOOKUP_TABLE_MAXIMUM, lookup_table_maximum, integer]
    - [LOOKUP_TABLE_MEDIAN, lookup_table_median, integer]
    - [LOOKUP_TABLE_K_VALUE, lookup_table_k_value, integer]
    - [LOOKUP_TABLE_NUMBER, lookup_table_number, integer]
    - [ADC_CONVERSION_SETTINGS, adc_conversion_settings, text]
    - [FPA_POSITIVE_Y_TEMPERATURE, fpa_positive_y_temperature, real]
    - [FPA_NEGATIVE_Y_TEMPERATURE, fpa_negative_y_temperature, real]
    - [FPE_TEMPERATURE, fpe_temperature, real]
    - [IEA_TEMPERATURE, iea_temperature, real]
    - [IEA_PWS_BOARD_TEMPERATURE, iea_pws_board_temperature, real]
    - [CPMM_PWS_BOARD_TEMPERATURE, cpmm_pws_board_temperature, real]
    - [SAMPLE_BITS, sample_bits, integer]
    - [EMISSION_ANGLE, emission_angle, real]
    - [INCIDENCE_ANGLE, incidence_angle, real]
    - [PHASE_ANGLE, phase_angle, real]
    - [MINIMUM_LATITUDE, minimum_latitude, real]
    - [MAXIMUM_LATITUDE, maximum_latitude, real]
    - [MINIMUM_LONGITUDE, minimum_longitude, real]
    - [MAXIMUM_LONGITUDE, maximum_longitude, real]
    - [SPACECRAFT_ALTITUDE, spacecraft_altitude, real]
    - [TARGET_CENTER_DISTANCE, target_center_distance, real]
    - [SLANT_DISTANCE, slant_distance, real]
    - [SUB_SOLAR_AZIMUTH, sub_solar_azimuth, real]
    - [SUB_SOLAR_LATITUDE, sub_solar_latitude, real]
    - [SUB_SOLAR_LONGITUDE, sub_solar_longitude, real]
    - [SUB_SPACECRAFT_LATITUDE, sub_spacecraft_latitude, real]
    - [SUB_SPACECRAFT_LONGITUDE, sub_spacecraft_longitude, real]
    - [SOLAR_DISTANCE, solar_distance, real]
    - [SOLAR_LONGITUDE, solar_longitude, real]
    - [LOCAL_TIME, local_time, real]
    - [STEREO_FLAG, stereo_flag, text]

scale_factors:
    SPACECRAFT_ALTITUDE: 1000 # km to m
    TARGET_CENTER_DISTANCE: 1000 # km to m
    SLANT_DISTANCE: 1000 # km to m
    SOLAR_DISTANCE: 149597870700 # au to m

index:
    - observation_id

segmentation:
    resolution: 50000
