[tool.poetry]
name = "hypster"
version = "0.0.4"
description = "HyPSTER is a brand new Python package that helps you find compact and accurate ML Pipelines while staying light and efficient"
authors = ["Gilad Rubin <gilad.rubin@gmail.com>"]
maintainers = ["Tal Peretz"]
homepage = "https://github.com/gilad-rubin/hypster"
license = "MIT"

[tool.poetry.dependencies]
python = ">= 3.5.7, <=3.8"
scikit-learn = "^0.22"
pandas = "^0.25.3"
optuna = "^0.19.0"
numpy = "^1.18.0"
scipy = "^1.4.1"
category_encoders = "^2.1.0"
lightgbm = "^2.3.1"
xgboost = "^0.90"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
pytest-xdist = "^1.31.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
