# Base Configuration file for artellapipe-tools-playblastmanager in Solstice

# Defines icon of the tool
icon: playblastmanager

# URL to tool documentation web page
url: https://solstice-short-film.github.io/solstice-docs/pipeline/pipeline/tools/playblastmanager/