# Base Configuration file for artellapipe-tools-assetsmanager in Solstice

# Defines icon of the tool
icon: assetsmanager

# URL to tool documentation web page
url: https://solstice-short-film.github.io/solstice-docs/pipeline/pipeline/tools/assetsmanager/