[tool.poetry]
name = "mazel"
version = "0.0.1"
description = "Makefile caller"
authors = ["John Paulett <john@paulett.org>"]
license = "BSD-3-Clause"

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]


[tool.poetry.scripts]
mazel = 'mazel:main'

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
