[tool.poetry]
name = "test_travis"
version = "0.1.1"
description = "A cookiecutter template for Python project"
authors = [
    "lin-zone <z_one10@163.com>",
]
license = "MIT license"
readme = "README.md"
repository = "https://github.com/lin-zone/test_travis"
keywords = ["packaging", "dependency", "poetry", "setuptools", "pip"]

[tool.poetry.dependencies]
python = "^3.6"
autopep8 = "*"
jinja2 = "*"
poetry = "*"

[tool.poetry.dev-dependencies]
pytest = "*"
pytest-cov = "*"

[tool.poetry.scripts]
poetry-setup = "poetry_setup.core:main"