[project]
name = "surepy"
version = "0.1.9"
description = "Library to interact with the flaps & doors from Sure Petcare."
authors = [
    "Ben Lebherz <git@benleb.de>"
]
license = "MIT"
readme = "README.md"
python = "^3.7"
homepage = "https://github.com/benleb/surepy"
repository = "https://github.com/benleb/surepy"
documentation = "https://github.com/benleb/surepy"

keywords = ["cat", "surepetcare", "home-assistant"]

classifiers = [
    "Topic :: Software Development",
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.7",
    "Topic :: Software Development :: Libraries :: Python Modules",
]

# Requirements
[dependencies]

[dev-dependencies]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"


[tool.black]
line-length = 88
target_version = ["py37"]
include = '\.pyi?$'
exclude = '''

(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
  )/
)
'''
