# coding: utf-8

"""
    Octopus Server API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2019.6.7+Branch.tags-2019.6.7.Sha.aa18dc6809953218c66f57eff7d26481d9b23d6a
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class LibraryVariableSetReleaseUsageEntry(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'release_id': 'str',
        'release_version': 'str'
    }

    attribute_map = {
        'release_id': 'ReleaseId',
        'release_version': 'ReleaseVersion'
    }

    def __init__(self, release_id=None, release_version=None):  # noqa: E501
        """LibraryVariableSetReleaseUsageEntry - a model defined in Swagger"""  # noqa: E501

        self._release_id = None
        self._release_version = None
        self.discriminator = None

        if release_id is not None:
            self.release_id = release_id
        if release_version is not None:
            self.release_version = release_version

    @property
    def release_id(self):
        """Gets the release_id of this LibraryVariableSetReleaseUsageEntry.  # noqa: E501


        :return: The release_id of this LibraryVariableSetReleaseUsageEntry.  # noqa: E501
        :rtype: str
        """
        return self._release_id

    @release_id.setter
    def release_id(self, release_id):
        """Sets the release_id of this LibraryVariableSetReleaseUsageEntry.


        :param release_id: The release_id of this LibraryVariableSetReleaseUsageEntry.  # noqa: E501
        :type: str
        """

        self._release_id = release_id

    @property
    def release_version(self):
        """Gets the release_version of this LibraryVariableSetReleaseUsageEntry.  # noqa: E501


        :return: The release_version of this LibraryVariableSetReleaseUsageEntry.  # noqa: E501
        :rtype: str
        """
        return self._release_version

    @release_version.setter
    def release_version(self, release_version):
        """Sets the release_version of this LibraryVariableSetReleaseUsageEntry.


        :param release_version: The release_version of this LibraryVariableSetReleaseUsageEntry.  # noqa: E501
        :type: str
        """

        self._release_version = release_version

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(LibraryVariableSetReleaseUsageEntry, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, LibraryVariableSetReleaseUsageEntry):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
