cfg_title = "24oct"

[inputs]
stop1 = "Empty"
stop2 = "PMT2"
stop3 = "Empty"
stop4 = "Empty"
stop5 = "Empty"
start = "PMT1"

[image]
num_of_frames = 1
x_pixels = 512
y_pixels = 512
z_pixels = 10
imaging_software = "ScanImage"

[outputs]
data_filename = "/data/Lior/lst/2019/2019_10_24/P1EP2/650k sweeps/alpaca_hair_512l512px_650k_sweeps_60us_sweep_P1EP2_018.lst"
summed = true
memory = false
stack = true
flim = false

[advanced]
debug = false
phase = -0.3
reprate = 80000000.0
gating = false
binwidth = 1e-10
tag_freq = 189900.0
tag_pulses = 1
tag_offset = 0
fill_frac = 72.0
bidir = true
keep_unidir = false
flim = false
censor = false
line_freq = 7930.0
sweeps_as_lines = true
frame_delay = 0.001
interleaved = false

[tagbits]
tag_bits = false

[tagbits.group1]
label1 = "None"
start1 = 1
end1 = 3

[tagbits.group2]
label2 = "None"
start2 = 4
end2 = 5

[tagbits.group3]
label3 = "None"
start3 = 6
end3 = 16
