cfg_title = "FLIM_LPP1024"

[inputs]
stop1 = "PMT1"
stop2 = "PMT2"
stop3 = "Empty"
stop4 = "Empty"
stop5 = "Empty"
start = "Lines"

[image]
num_of_frames = 1
x_pixels = 1024
y_pixels = 1024
z_pixels = 10
imaging_software = "ScanImage"

[outputs]
data_filename = "/data/Lior/lst/2019/2019_10_29/FLIM_ports_mouse_25x_obj_LP1P2_1024l1024px_840nm_6x_zoom_USE_THIS_FOV_017.lst"
summed = true
memory = false
stack = false

[advanced]
debug = false
phase = -0.2
reprate = 80000000.0
gating = false
binwidth = 1e-10
tag_freq = 189900.0
tag_pulses = 1
tag_offset = 0
fill_frac = 72.0
bidir = true
keep_unidir = false
flim = true
censor = false
line_freq = 7930.0
sweeps_as_lines = false
frame_delay = 0.001
interleaved = false

[tagbits]
tag_bits = false

[tagbits.group1]
label1 = "None"
start1 = 1
end1 = 3

[tagbits.group2]
label2 = "None"
start2 = 4
end2 = 5

[tagbits.group3]
label3 = "None"
start3 = 6
end3 = 16
