cfg_title = "PTL2048189k"

[inputs]
stop1 = "TAG Lens"
stop2 = "Lines"
stop3 = "Empty"
stop4 = "Empty"
stop5 = "Empty"
start = "PMT1"

[image]
num_of_frames = 1
x_pixels = 2048
y_pixels = 512
z_pixels = 132
imaging_software = "ScanImage"

[outputs]
data_filename = "/data/Lior/lst/2019/2019_04_30/PTL_mouse_vasculature_2048lines_10xobj_1x_zoom_189kHz62p_003.lst"
summed = true
memory = false
stack = true

[advanced]
debug = false
phase = -0.3
reprate = 80000000.0
gating = false
binwidth = 1e-10
tag_freq = 189000.0
tag_pulses = 1
tag_offset = 0
fill_frac = 72.0
bidir = true
keep_unidir = false
flim = false
censor = false
line_freq = 7930.0
sweeps_as_lines = false
frame_delay = 0.001
interleaved = false

[tagbits]
tag_bits = false

[tagbits.group1]
label1 = "None"
start1 = 1
end1 = 3

[tagbits.group2]
label2 = "None"
start2 = 4
end2 = 5

[tagbits.group3]
label3 = "None"
start3 = 6
end3 = 16
