cfg_title = "TLP1024l1024c128z_189k"

[inputs]
stop1 = "Lines"
stop2 = "PMT1"
stop3 = "Empty"
stop4 = "Empty"
stop5 = "Empty"
start = "TAG Lens"

[image]
num_of_frames = 1
x_pixels = 1024
y_pixels = 1024
z_pixels = 128
imaging_software = "ScanImage"

[outputs]
data_filename = "/data/Lior/lst/2019/2019_12_18/GCaMP6s_mouse_TLP189k62p_3x_zoom_1024l1024px_58p28fps_1slow_FOV1_nominal_depth011.lst"
summed = true
memory = false
stack = true
flim = false

[advanced]
debug = false
phase = -0.4
reprate = 80000000.0
gating = false
binwidth = 1e-10
tag_freq = 189000.0
tag_pulses = 1
tag_offset = 0
fill_frac = 72.0
bidir = true
keep_unidir = false
flim = false
censor = false
line_freq = 7930.0
sweeps_as_lines = false
frame_delay = 0.001
interleaved = false

[tagbits]
tag_bits = false

[tagbits.group1]
label1 = "None"
start1 = 1
end1 = 3

[tagbits.group2]
label2 = "None"
start2 = 4
end2 = 5

[tagbits.group3]
label3 = "None"
start3 = 6
end3 = 16
