[tool.poetry]
name = "kangry-pomodoro"
version = "0.1.1"
description = ""
authors = ["Gregory <netsafe.g@gmail.com>"]
packages = [
    {include = "kangry_pomodoro"},
    {include = "static/icon.png"},
]

[tool.poetry.dependencies]
python = "^3.7"
click = "^7.0"
pyqt5 = "^5.13"
notify2 = "^0.3.1"
dbus-python = "^1.2"

[tool.poetry.dev-dependencies]
pytest = "^3.0"
pylint = "^2.4"

[tool.poetry.scripts]
kangry-pomodoro = "kangry_pomodoro.app:main"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
