# coding: utf-8

"""
    Octopus Server API Client

    Python API Client for Octopus Deploy (v2019.6.7) (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2019.6.7+Branch.tags-2019.6.7.Sha.aa18dc6809953218c66f57eff7d26481d9b23d6a
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    Modified by: d.jain
"""


from setuptools import setup, find_packages  # noqa: H301

NAME = "octopus-deploy-swagger-client"
VERSION = "1.1.0"
# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools

REQUIRES = [
    "certifi>=2017.4.17",
    "python-dateutil>=2.1",
    "six>=1.10",
    "urllib3>=1.23"
]
    

setup(
    name=NAME,
    version=VERSION,
    author="devanjain",
    author_email="jain.devan@gmail.com",
    description="Octopus Server API",
    url="",
    keywords=["Swagger", "Octopus Server API"],
    install_requires=REQUIRES,
    packages=find_packages(),
    include_package_data=True,
    long_description="""\
    Python API Client for Octopus Deploy (v2019.6.7) (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501
    """
)
