[tool.poetry]
name = "GMConfig"
version = "0.4.0"
description = "My lazy mans config loading and exporting module"

authors = [
    "GeekMasher"
]

license = "MIT"

readme = "README.md"

repository = "https://github.com/GeekMasher/GMConfig"

keywords = ["configuration", "gmconfig"]

classifiers = [
    "Development Status :: 4 - Beta",
    "Operating System :: Unix",
    "Operating System :: POSIX :: Linux",
    "Operating System :: Microsoft :: Windows",
    "Topic :: Software Development :: Build Tools",
    "Topic :: Software Development :: Libraries :: Python Modules",
]

[tool.poetry.dependencies]
python = "^3.7"
pyyaml = "^5.1"
toml = "^0.10.0"

[tool.poetry.dev-dependencies]
pytest = "^5.1"
black = "19.3b0"
mypy = "^0.720.0"

[tool.poetry.scripts]
poetry = "poetry.console:main"
test = 'python -m unittest discover tests -p test_*.py'
test-types = 'mypy gmconfig'
lint = 'black gmconfig'

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
