dist: trusty
group: edge
os:
    - linux
    # travis does not support python on osx yet (https://github.com/travis-ci/travis-ci/issues/4729)
language: python
python:
    - "3.6"
addons:
    chrome: stable
before_install:
    # - sudo apt-get update
    # - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
    # - wget https://repo.continuum.io/miniconda/Miniconda3-4.5.11-Linux-x86_64.sh -O miniconda.sh
    # - bash miniconda.sh -b -p $HOME/miniconda
    # - export PATH="$HOME/miniconda/bin:$PATH"
    # - hash -r
    # - conda config --set always_yes yes --set changeps1 no
    # - conda update -q conda
    #   #- conda info -a
    # - pip install docker rq pyyaml psutil tqdm nose fasteners pygments networkx pydot pydotplus
    # - pip install entrypoints jupyter coverage codacy-coverage pytest pytest-cov python-coveralls
    # - conda install -q pandas numpy
    # - conda install -c r r-essentials r-feather
    # - conda install -c conda-forge feather-format
    # # SoS Notebook
    # - pip install jedi notebook nbconvert nbformat pyyaml psutil tqdm scipy markdown matplotlib
    # - sudo apt-get install libmagickwand-dev libmagickcore5-extra graphviz
    # - pip install pygments ipython wand graphviz
    # - pip install git+https://github.com/vatlab/sos.git
    # - pip install git+https://github.com/vatlab/sos-bash.git
    # - pip install git+https://github.com/vatlab/sos-python.git
    # - pip install git+https://github.com/vatlab/sos-r.git
    # - pip install selenium
    # - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
    # - wget https://chromedriver.storage.googleapis.com/73.0.3683.20/chromedriver_linux64.zip -P ~/
    # - unzip ~/chromedriver_linux64.zip -d ~/
    # - rm ~/chromedriver_linux64.zip
    # - sudo mv -f ~/chromedriver /usr/local/share/
    # - sudo chmod +x /usr/local/share/chromedriver
    # - sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver
    # - "export DISPLAY=:99.0"
    # - "sh -e /etc/init.d/xvfb start"
    # - sleep 3


sudo: required
services:
    - docker
install:
    - docker network create sosnet
    - docker pull mdabioinfo/sos_notebook_test:latest
    - docker pull mdabioinfo/eg_sshd:latest
    - cd development
    - export COMPOSE_PROJECT_NAME=sosnotebook
    - docker-compose up -d
    - cd ..
    - docker cp . sosnotebook_sos-notebook_1:/home/jovyan
    - docker exec -u root sosnotebook_sos-notebook_1 sh ./development/install_sos_notebook.sh
before_script:
    # - cd test
    # - sh build_test_docker.sh
script:
    #- docker exec -u root  sosnotebook_sos-notebook_1  pytest ./test -x -v --cov sos_notebook --cov-report=term-missing
    - docker exec -u root  sosnotebook_sos-notebook_1 mkdir -p /home/jovyan/.sos
    - docker exec -u root  sosnotebook_sos-notebook_1 mkdir -p /home/jovyan/.local
    - docker exec -u root  sosnotebook_sos-notebook_1 chown -R jovyan:users /home/jovyan/.sos/
    - docker exec -u root  sosnotebook_sos-notebook_1 chown -R jovyan:users /home/jovyan/.local/
    - docker exec -u root  sosnotebook_sos-notebook_1 chown -R jovyan:users /home/jovyan/test/
    - docker exec sosnotebook_sos-notebook_1 bash -c 'cd test && pytest -v'
after_success:
    - coverage combine
    - coveralls

notifications:
    email:
        recipients:
            - ben.bob@gmail.com
            - junma80@gmail.com
        on_success: never
        on_failure: always

