
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-12-27T10:53:20-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "45eb9bf12c322be429a13979967b5854ceca31f1",
 "version": "2.9.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
