
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-12-31T16:27:53-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "049a630df82f487a9af122c6bee4b93fca90a03c",
 "version": "2019.12.12"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
