[build-system]
requires = [ "poetry>=0.12",]
build-backend = "poetry.masonry.api"

[tool.poetry]
name = "brad"
version = "0.0.0-a0"
description = "Brad is a Python package for Bootstrap, permutation tests and other resampling functions."
authors = [ "tcbegley <tomcbegley@gmail.com>",]
license = "MIT"
classifiers = [ "Development Status :: 3 - Alpha", "License :: OSI Approved :: MIT License",]

[tool.black]
line-length = 79
target-version = [ "py36",]

[tool.isort]
include_trailing_comma = true
line_length = 79
multi_line_output = 3
known_third_party = []

[tool.poetry.dependencies]
python = "^3.7"
numpy = "^1.18.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
black = "^19.10b0"
flake8 = "^3.7.9"
isort = "^4.3.21"
