[tool.commitizen]
version = "0.1.5"
tag_format = "v$version"
files = [
  "pyproject.toml:version",
  "jiratag_commitizen/__version__.py"
]

[tool.black]
line-length = 88
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
  # The following are specific to Black, you probably don't want those.
  | blib2to3
  | tests/data
  | profiling
)/
'''

[tool.poetry]
name = "jiratag-commitizen"
version = "0.1.5"
description = "Python commitizen client tool"
authors = ["Santiago Fraire <santiwilly@gmail.com>"]
license = "MIT"
keywords = ["commitizen", "conventional", "commits", "git", "jira"]
readme = "README.rst"
homepage = "https://github.com/cgutierrezpa/jiratag-commitizen"
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: Implementation :: CPython",
]

[tool.poetry.dependencies]
python = "^3.6"
questionary = "^1.0"
decli = "^0.5.0"
colorama = "^0.4.1"
termcolor = "^1.1"
packaging = "^19.0"
tomlkit = "^0.5.3"

[tool.poetry.dev-dependencies]
ipython = "^7.2"
black = "^19.3b0"
pytest = "^5.0"
flake8 = "^3.6"
pytest-cov = "^2.6"
pytest-mock = "^1.10"
codecov = "^2.0"
mypy = "^0.730"
mkdocs = "^1.0"
mkdocs-material = "^4.1"

[tool.poetry.scripts]
cz = "jiratag_commitizen.cli:main"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
