# -*- coding: utf-8 -*-
from distutils.core import setup

packages = \
['jiratag_commitizen',
 'jiratag_commitizen.commands',
 'jiratag_commitizen.cz',
 'jiratag_commitizen.cz.conventional_commits',
 'jiratag_commitizen.cz.jira',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.IPython',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.IPython.core',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.IPython.core.magics',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.IPython.core.tests',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.IPython.extensions',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.IPython.extensions.tests',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.IPython.external',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.IPython.external.decorators',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.IPython.kernel',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.IPython.lib',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.IPython.lib.tests',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.IPython.sphinxext',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.IPython.terminal',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.IPython.terminal.pt_inputhooks',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.IPython.terminal.tests',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.IPython.testing',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.IPython.testing.plugin',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.IPython.testing.tests',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.IPython.utils',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.IPython.utils.tests',
 'jiratag_commitizen.venv.lib.python3.7.site-packages._pytest',
 'jiratag_commitizen.venv.lib.python3.7.site-packages._pytest._code',
 'jiratag_commitizen.venv.lib.python3.7.site-packages._pytest._io',
 'jiratag_commitizen.venv.lib.python3.7.site-packages._pytest.assertion',
 'jiratag_commitizen.venv.lib.python3.7.site-packages._pytest.config',
 'jiratag_commitizen.venv.lib.python3.7.site-packages._pytest.mark',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.atomicwrites',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.attr',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.backcall',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.blib2to3',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.blib2to3.pgen2',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.cachecontrol',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.cachecontrol.caches',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.cachy',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.cachy.contracts',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.cachy.serializers',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.cachy.stores',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.certifi',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.chardet',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.chardet.cli',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.cleo',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.cleo.commands',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.cleo.commands.completions',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.cleo.descriptors',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.cleo.exceptions',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.cleo.formatters',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.cleo.helpers',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.cleo.inputs',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.cleo.outputs',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.cleo.questions',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.cleo.styles',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.cleo.testers',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.cleo.validators',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.click',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.codecov',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.colorama',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.coverage',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.decli',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.flake8',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.flake8.api',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.flake8.formatting',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.flake8.main',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.flake8.options',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.flake8.plugins',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.html5lib',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.html5lib._trie',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.html5lib.filters',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.html5lib.treeadapters',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.html5lib.treebuilders',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.html5lib.treewalkers',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.htmlmin',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.htmlmin.python3html',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.idna',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.importlib_metadata',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.importlib_metadata.docs',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.importlib_metadata.tests',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.importlib_metadata.tests.data',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.ipython_genutils',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.ipython_genutils.testing',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.ipython_genutils.tests',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.jedi',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.jedi.api',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.jedi.common',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.jedi.evaluate',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.jedi.evaluate.compiled',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.jedi.evaluate.compiled.subprocess',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.jedi.evaluate.context',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.jedi.evaluate.gradual',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.jedi.plugins',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.jinja2',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.jsmin',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.jsonschema',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.jsonschema.benchmarks',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.jsonschema.tests',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.livereload',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.livereload.management.commands',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.lockfile',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.markdown',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.markdown.extensions',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.markupsafe',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.material',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.mkdocs',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.mkdocs.commands',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.mkdocs.config',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.mkdocs.contrib',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.mkdocs.contrib.search',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.mkdocs.structure',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.mkdocs.tests',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.mkdocs.tests.config',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.mkdocs.tests.structure',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.mkdocs.tests.utils',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.mkdocs.themes',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.mkdocs.themes.mkdocs',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.mkdocs.themes.readthedocs',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.mkdocs.utils',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.mkdocs_minify_plugin',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.more_itertools',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.more_itertools.tests',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.msgpack',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.mypy',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.mypy.dmypy',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.mypy.plugins',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.mypy.server',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.mypy.test',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.mypyc',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.mypyc.test',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.packaging',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.parso',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.parso.pgen2',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.parso.python',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.pastel',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.pep562',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.pexpect',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.pip',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.pip._vendor',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.pip.commands',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.pip.compat',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.pip.models',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.pip.operations',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.pip.req',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.pip.utils',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.pip.vcs',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.pkg_resources',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.pkg_resources._vendor',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.pkg_resources._vendor.packaging',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.pkg_resources.extern',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.pkginfo',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.pkginfo.tests',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.pluggy',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.poetry',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.poetry.console',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.poetry.console.commands',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.poetry.console.commands.cache',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.poetry.console.commands.debug',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.poetry.console.commands.self',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.poetry.console.styles',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.poetry.installation',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.poetry.io',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.poetry.json',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.poetry.layouts',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.poetry.masonry',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.poetry.masonry.builders',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.poetry.masonry.publishing',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.poetry.masonry.utils',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.poetry.mixology',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.poetry.packages',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.poetry.packages.constraints',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.poetry.packages.utils',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.poetry.puzzle',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.poetry.puzzle.operations',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.poetry.repositories',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.poetry.semver',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.poetry.spdx',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.poetry.utils',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.poetry.vcs',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.poetry.version',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.prompt_toolkit',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.prompt_toolkit.application',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.prompt_toolkit.clipboard',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.prompt_toolkit.completion',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.prompt_toolkit.contrib',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.prompt_toolkit.contrib.completers',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.prompt_toolkit.contrib.regular_languages',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.prompt_toolkit.contrib.telnet',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.prompt_toolkit.eventloop',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.prompt_toolkit.filters',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.prompt_toolkit.formatted_text',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.prompt_toolkit.input',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.prompt_toolkit.key_binding',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.prompt_toolkit.key_binding.bindings',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.prompt_toolkit.layout',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.prompt_toolkit.lexers',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.prompt_toolkit.output',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.prompt_toolkit.shortcuts',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.prompt_toolkit.shortcuts.progress_bar',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.prompt_toolkit.styles',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.prompt_toolkit.widgets',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.ptyprocess',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.py',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.py._code',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.py._io',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.py._log',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.py._path',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.py._process',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.py._vendored_packages',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.pyflakes',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.pyflakes.scripts',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.pyflakes.test',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.pygments',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.pygments.filters',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.pygments.formatters',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.pygments.lexers',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.pygments.styles',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.pymdownx',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.pyrsistent',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.pytest_cov',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.pytest_mock',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.questionary',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.questionary.prompts',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.requests',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.requests_toolbelt',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.requests_toolbelt.adapters',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.requests_toolbelt.auth',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.requests_toolbelt.cookies',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.requests_toolbelt.downloadutils',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.requests_toolbelt.multipart',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.requests_toolbelt.threaded',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.requests_toolbelt.utils',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.setuptools',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.setuptools._vendor',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.setuptools._vendor.packaging',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.setuptools.command',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.setuptools.extern',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.shellingham',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.shellingham.posix',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.src',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.tests.prompts',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.toml',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.tomlkit',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.tornado',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.tornado.platform',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.tornado.test',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.traitlets',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.traitlets.config',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.traitlets.config.tests',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.traitlets.tests',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.traitlets.utils',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.traitlets.utils.tests',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.typed_ast',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.urllib3',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.urllib3.contrib',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.urllib3.contrib._securetransport',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.urllib3.packages',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.urllib3.packages.backports',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.urllib3.packages.ssl_match_hostname',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.urllib3.util',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.wcwidth',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.wcwidth.tests',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.webencodings',
 'jiratag_commitizen.venv.lib.python3.7.site-packages.yaml']

package_data = \
{'': ['*']}

install_requires = \
['colorama>=0.4.1,<0.5.0',
 'decli>=0.5.0,<0.6.0',
 'packaging>=19.0,<20.0',
 'questionary>=1.0,<2.0',
 'termcolor>=1.1,<2.0',
 'tomlkit>=0.5.3,<0.6.0']

entry_points = \
{'console_scripts': ['cz = jiratag_commitizen.cli:main']}

setup_kwargs = {
    'name': 'jiratag-commitizen',
    'version': '0.1.5',
    'description': 'Python commitizen client tool',
    'long_description': '====================\nJiratag Commitizen\n====================\n\nThis a simple project forked from https://Woile.github.io/commitizen/\nthat simply adds a step in the default conventional-commit pipeline to\nindicate the Jira Issue tag in order for the commit to include the link\nto the issue so that is quickly accessed from the Bitbucket commit log.\n\n-----------\n\n**Documentation**: https://Woile.github.io/commitizen/\n',
    'author': 'Santiago Fraire',
    'author_email': 'santiwilly@gmail.com',
    'maintainer': None,
    'maintainer_email': None,
    'url': 'https://github.com/cgutierrezpa/jiratag-commitizen',
    'packages': packages,
    'package_data': package_data,
    'install_requires': install_requires,
    'entry_points': entry_points,
    'python_requires': '>=3.6,<4.0',
}


setup(**setup_kwargs)
