
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-12-18T13:34:51+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "3e6605b017ecf01c8e89c633a2a7f658bfba0af5",
 "version": "0.3.18"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
