language: python

matrix:
  include:
    - name: "Python2.7 + PCL1.8 + Numpy1.11"
      dist: bionic
      python: 2.7
      env: NUMPY=1.11

    - name: "Python3.5 + PCL1.6 + Numpy1.11"
      python: 3.5
      env: NUMPY=1.11 # RUN_COVERAGE=yes, BUILD_DOC=yes

    - name: "Python3.6 + PCL1.7 + Numpy1.13"
      dist: xenial
      python: 3.6
      env: NUMPY=1.13

    - name: "Python3.7 + PCL1.8 + Numpy1.15"
      dist: bionic
      python: 3.7
      env: NUMPY=1.15

  # - os: osx
  #   osx_image: xcode10.2  # Python 3.7.2 running on macOS 10.14.3
  #   language: shell

  # - os: windows
  #   python: 3.6
  #   env: NUMPY=1.12 

branches:
  only:
    - master

before_install:
  - sudo apt update
  - sudo apt install -y libpcl-dev
  - pip install numpy==$NUMPY cython scikit-build
  - if [ "$RUN_COVERAGE" == "yes" ]; then pip install coveralls pytest-cov -q; fi

install:
  - pip install .

script:
  - if [ "$RUN_COVERAGE" == "yes" ]; then
      py.test test/ --cov;
    else
      py.test test/;
    fi

after_success:
  - if [ "$RUN_COVERAGE" == "yes" ]; then coveralls; fi
  # TODO: push dist packages directly to PyPI
