# Generated by Django 2.2.6 on 2019-12-21 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0002_auto_20191221_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='amount',
            field=models.IntegerField(blank=True, verbose_name='Source amount'),
        ),
    ]
