[tool.poetry]
name = "longhow"
version = "0.1.0"
description = "A simple decorator to measure a function execution time"
authors = ["Tendi Muchenje <tendi@outlook.com>"]
license = "MIT"
readme = "README.rst"

[tool.poetry.dependencies]
python = "^3.7"
pendulum = "^2.0.5"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
flake8 = "^3.7.9"
black = "^19.10b0"
pendulum = "^2.0.5"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
