version: '3'

services:
    sos-notebook:
        build:
            context: ./sos_notebook_test
        image: mdabioinfo/sos_notebook_test:latest
        restart: "no"
        shm_size:
            8gb
        networks:
          - sosnet
    sos:
        build:
            context: ./eg_sshd
        image: mdabioinfo/eg_sshd:latest
        hostname: sos

        restart: always
        networks:
          - sosnet


networks:
  sosnet:
    external: true
