
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-12-22T16:18:52-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "486abf433c4f53fee931cf0658d4812a5c93a435",
 "version": "0.2.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
