# Generated by Django 2.2 on 2019-06-18 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0002_auto_20190617_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetcategories',
            name='amount',
            field=models.FloatField(default=1, verbose_name='Category Amount'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='budgetcategories',
            name='category_type',
            field=models.CharField(choices=[('ANNUAL', 'Annual'), ('MONTH', 'Monthly')], default=1, max_length=6, verbose_name='Category Type'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='budgetcategories',
            name='category',
            field=models.CharField(max_length=100, verbose_name='Budget Category'),
        ),
    ]
