# Generated by Django 2.2 on 2019-06-18 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0004_auto_20190617_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetcategories',
            name='amount',
            field=models.FloatField(verbose_name='category Amount'),
        ),
        migrations.AlterField(
            model_name='budgetcategories',
            name='category',
            field=models.CharField(max_length=100, verbose_name='budget Category'),
        ),
        migrations.AlterField(
            model_name='budgetcategories',
            name='category_type',
            field=models.CharField(choices=[('ANNUAL', 'Annual'), ('MONTH', 'Monthly')], max_length=6, verbose_name='category Type'),
        ),
    ]
