
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-12-18T18:06:03+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "8f72ee6550b605fe3894c5b575ce3b3c88255fd1",
 "version": "v0.4.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
