[tool.poetry]
name = "russe-pack"
version = "0.1.0"
description = ""
authors = ["Colin Goutte <cgte@bk.ru>"]

[tool.poetry.dependencies]
python = "^3.6"
bs4 = "^0.0.1"
selenium = "^3.141.0"
lxml = "^4.4.2"
requests = "^2.22.0"

[tool.poetry.dev-dependencies]
pytest = "^4.6"
ipdb = "^0.12.3"
black = "^19.10b0"

[tool.poetry.scripts]
get_russianpodcasts = 'russe_pack.get_episodes:main'


[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

