
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-12-29T23:04:32+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "942fc4dbce4a9f2cf9ae1023447ae12e22bc9e71",
 "version": "2019.12.29.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
