[tool.poetry]
name = "sql2json"
version = "0.1.1"
description = "SQL query to JSON"
authors = ["Francisco Pérez <fsistemas@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.5"
SQLAlchemy = "^1.3.12"
click = "^7.0"

[tool.poetry.dev-dependencies]


[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
