[tool.poetry]
name = "Lucidic"
version = "0.1.0"
description = "Lucidic is a Python dictionary utility designed to simplify dictionary operations and comparisons"
license = "GPL-3.0-or-later"
authors = ["Rich Nason <rnason@cloudmage.io>"]
readme = "README.md"
include = [
    "CHANGELOG.md"
]
repository = "Lucidic"
homepage = "https://github.com/TheCloudMage/PyPkgs-Lucidic"

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]
pytest = "^4.6"

[tool.poetry.urls]
"Releases" = "https://github.com/TheCloudMage/PyPkgs-Lucidic/releases"
"Bug Tracking" = "https://github.com/TheCloudMage/PyPkgs-Lucidic/issues"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
