
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-12-26T10:36:33-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "750cf5e90fd3e75e47d1f3d212679a60d901cfbd",
 "version": "0.2.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
