environment:
  matrix:
    # We only test on one Python version as builds are slow.
    - PYTHON_VERSION: "3.7"

init:
  - cmd: SET PYTHON=C:\\Miniconda37-x64
  - cmd: ECHO Using %PYTHON%

install:
  - cmd: SET PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%
  - cmd: conda config --add channels conda-forge
  - cmd: conda create --yes -n testenv python=%PYTHON_VERSION%
  - cmd: activate testenv
  - cmd: conda install --yes --file=requirements\conda-minimal.txt
  - cmd: conda info -a
  - cmd: python --version

build_script:
  - cmd: python -m nose -vs

after_test:
  - cmd: python setup.py bdist_wheel
