# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc_data.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='rpc_data.proto',
  package='rpc_data',
  syntax='proto3',
  serialized_pb=_b('\n\x0erpc_data.proto\x12\x08rpc_data\"\x1a\n\x07Request\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x18\n\x05Reply\x12\x0f\n\x07message\x18\x01 \x01(\t2A\n\x07Greeter\x12\x36\n\x0ehandle_request\x12\x11.rpc_data.Request\x1a\x0f.rpc_data.Reply\"\x00\x42-\n\x19io.grpc.examples.rpc_dataB\x08rpc_dataP\x01\xa2\x02\x03HLWb\x06proto3')
)




_REQUEST = _descriptor.Descriptor(
  name='Request',
  full_name='rpc_data.Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='rpc_data.Request.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=54,
)


_REPLY = _descriptor.Descriptor(
  name='Reply',
  full_name='rpc_data.Reply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='rpc_data.Reply.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=56,
  serialized_end=80,
)

DESCRIPTOR.message_types_by_name['Request'] = _REQUEST
DESCRIPTOR.message_types_by_name['Reply'] = _REPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), dict(
  DESCRIPTOR = _REQUEST,
  __module__ = 'rpc_data_pb2'
  # @@protoc_insertion_point(class_scope:rpc_data.Request)
  ))
_sym_db.RegisterMessage(Request)

Reply = _reflection.GeneratedProtocolMessageType('Reply', (_message.Message,), dict(
  DESCRIPTOR = _REPLY,
  __module__ = 'rpc_data_pb2'
  # @@protoc_insertion_point(class_scope:rpc_data.Reply)
  ))
_sym_db.RegisterMessage(Reply)


DESCRIPTOR._options = None

_GREETER = _descriptor.ServiceDescriptor(
  name='Greeter',
  full_name='rpc_data.Greeter',
  file=DESCRIPTOR,
  index=0,
  serialized_start=82,
  serialized_end=147,
  methods=[
  _descriptor.MethodDescriptor(
    name='handle_request',
    full_name='rpc_data.Greeter.handle_request',
    index=0,
    containing_service=None,
    input_type=_REQUEST,
    output_type=_REPLY,
  ),
])
_sym_db.RegisterServiceDescriptor(_GREETER)

DESCRIPTOR.services_by_name['Greeter'] = _GREETER

# @@protoc_insertion_point(module_scope)
