[tool.poetry]
name = "xlsxreporter"
version = "0.1.3"
description = "A thin wrapper around xlsxwriter, to aid in generating row-by-row XLSX reports."
authors = ["Jonas Myrlund <myrlund@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.6"
xlsxwriter = "^1.1"

[tool.poetry.dev-dependencies]
pytest = "^3.0"
black = {version = "^18.3-alpha.0",allows-prereleases = true}

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
