#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['foxtail_blog', 'foxtail_blog.migrations', 'foxtail_blog.tests']

package_data = \
{'': ['*']}

install_requires = \
['django>=2.2',
 'django-markdownfield>=0.6.1',
 'django-taggit',
 'django-versatileimagefield',
 'django-crispy-forms',
 'django-recaptcha',
 'django-csp-helpers>=0.5.0',
 'django-published>=0.6.0']

extras_require = \
{'test': ['flit==2.1.0',
          'atoma==0.0.17',
          'coverage==5.0.1',
          'factory-boy==2.12.0',
          'django-environ==0.4.5',
          'pytest==5.3.2',
          'pytest-cov==2.8.1',
          'pytest-django==3.7.0',
          'pytest-factoryboy==2.0.3',
          'pytest-xdist==1.31.0',
          'selenium==3.141.0',
          'tox==3.14.3']}

setup(name='foxtail-blog',
      version='0.14.7',
      description='A simple blog for Django ',
      author='Luke Rogers',
      author_email='luke@dmptr.com',
      url='https://github.com/dmptrluke/foxtail-blog',
      packages=packages,
      package_data=package_data,
      install_requires=install_requires,
      extras_require=extras_require,
      python_requires='>=3.6',
     )
