
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-12-27T20:02:39+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "e1ac0e821e12b2b11b84811278bd73d4810b729e",
 "version": "2019.12.27.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
