[tool.poetry]
name = "fuzzysorteddict"
version = "1.1.0"
description = "A sorted dictionary with nearest-key lookup"
authors = ["NC State Aerial Robotics Club <aerialrobotics@ncsu.edu>"]
readme = "README.rst"
homepage = "https://github.com/ncsuarc/FuzzySortedDict"
keywords = ["dictionary"]

[tool.poetry.dependencies]
python = ">=3.5"
sortedcontainers = "^2.1.0"

[tool.poetry.dev-dependencies]
pytest = "^5.3.2"

[build-system]
requires = ["poetry>=1.0.0"]
build-backend = "poetry.masonry.api"
