# -*- coding: utf-8 -*-
from distutils.core import setup

packages = \
['chime_frb_api',
 'chime_frb_api.core',
 'chime_frb_api.distributor',
 'chime_frb_api.frb_master']

package_data = \
{'': ['*'],
 'chime_frb_api': ['tests/docker-compose.yml',
                   'tests/docker-compose.yml',
                   'tests/docker-compose.yml',
                   'tests/docker-compose.yml',
                   'tests/docker-compose.yml',
                   'tests/docker-compose.yml',
                   'tests/docker-compose.yml',
                   'tests/docker-compose.yml',
                   'tests/test_calibration.py',
                   'tests/test_calibration.py',
                   'tests/test_calibration.py',
                   'tests/test_calibration.py',
                   'tests/test_calibration.py',
                   'tests/test_calibration.py',
                   'tests/test_calibration.py',
                   'tests/test_calibration.py',
                   'tests/test_core.py',
                   'tests/test_core.py',
                   'tests/test_core.py',
                   'tests/test_core.py',
                   'tests/test_core.py',
                   'tests/test_core.py',
                   'tests/test_core.py',
                   'tests/test_core.py',
                   'tests/test_distributor.py',
                   'tests/test_distributor.py',
                   'tests/test_distributor.py',
                   'tests/test_distributor.py',
                   'tests/test_distributor.py',
                   'tests/test_distributor.py',
                   'tests/test_distributor.py',
                   'tests/test_distributor.py',
                   'tests/test_events.py',
                   'tests/test_events.py',
                   'tests/test_events.py',
                   'tests/test_events.py',
                   'tests/test_events.py',
                   'tests/test_events.py',
                   'tests/test_events.py',
                   'tests/test_events.py',
                   'tests/test_metrics.py',
                   'tests/test_metrics.py',
                   'tests/test_metrics.py',
                   'tests/test_metrics.py',
                   'tests/test_metrics.py',
                   'tests/test_metrics.py',
                   'tests/test_metrics.py',
                   'tests/test_metrics.py',
                   'tests/test_parameters.py',
                   'tests/test_parameters.py',
                   'tests/test_parameters.py',
                   'tests/test_parameters.py',
                   'tests/test_parameters.py',
                   'tests/test_parameters.py',
                   'tests/test_parameters.py',
                   'tests/test_parameters.py',
                   'tests/test_swarm.py',
                   'tests/test_swarm.py',
                   'tests/test_swarm.py',
                   'tests/test_swarm.py',
                   'tests/test_swarm.py',
                   'tests/test_swarm.py',
                   'tests/test_swarm.py',
                   'tests/test_swarm.py']}

install_requires = \
['pip>=19.2,<20.0', 'pyjwt>=1.7,<2.0', 'requests>=2.22,<3.0']

setup_kwargs = {
    'name': 'chime-frb-api',
    'version': '2019.12.11',
    'description': 'CHIME/FRB API',
    'long_description': '# CHIME/FRB API\n\n|   **`Build`**   | **`Coverage`**  |   **`Docs`**    |  **`Release`**  |   **`Style`**    |\n|-----------------|-----------------|-----------------|-----------------| -----------------|\n|[![Build Status](https://travis-ci.com/CHIMEFRB/frb-api.svg?token=mRNzzrGmJQewCpZQsov9&branch=master)](https://travis-ci.com/CHIMEFRB/frb-api)| [![Coverage Status](https://coveralls.io/repos/github/CHIMEFRB/frb-api/badge.svg?branch=master&t=uYdqsa)](https://coveralls.io/github/CHIMEFRB/frb-api?branch=master) | `Soon!`   | [![PyPI version](https://img.shields.io/pypi/v/chime-frb-api.svg)](https://pypi.org/project/chime-frb-api/) | [![Code style: black](https://img.shields.io/badge/code%20style-black-000000.svg)](https://black.readthedocs.io/en/stable/)\n\n--------\n\n`chime-frb-api` is a Python 3 library to access the all components spread throught the CHIME/FRB project. This library enables you interact with resources such as databases, event headers, calibration products, cluster jobs and the CHIME/FRB backend.\n\n## Install\n```\npip install chime-frb-api\n```\n\n## Usage\n```python\nfrom chime_frb_api import distributor\n\n# Create a distributor instance\ndistributor = distributor.Distributor(base_url="http://frb-vsop.chime:8002")\n\n# Create distributor\ndistributor.create_distributor("test")\n\n# Get status of the distributor\nstatus = distributor.get_status("test")\nprint(status)\n```\n\n## Documentation\nMore information will be added here soon.\n\n## Development\nComing Soon!\n\n\n',
    'author': 'Shiny Brar',
    'author_email': 'charanjotbrar@gmail.com',
    'url': 'https://github.com/CHIMEFRB/frb-api',
    'packages': packages,
    'package_data': package_data,
    'install_requires': install_requires,
    'python_requires': '>=3.6,<4.0',
}


setup(**setup_kwargs)
