repos:
- repo: https://github.com/ambv/black
  rev: 19.3b0
  hooks:
  - id: black
    language_version: python3
    language: python_venv
- repo: https://github.com/asottile/blacken-docs
  rev: v1.3.0
  hooks:
  - id: blacken-docs
    additional_dependencies: [black==19.3b0]
    language: python_venv
- repo: https://github.com/asottile/pyupgrade
  rev: v1.22.1
  hooks:
  - id: pyupgrade
    language: python_venv
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
  - id: trailing-whitespace
    language: python_venv
  - id: end-of-file-fixer
    language: python_venv
  - id: check-yaml
    language: python_venv
  - id: check-ast
    language: python_venv
  - id: mixed-line-ending
    language: python_venv
  - id: debug-statements
    language: python_venv
  - id: flake8
    language: python_venv
    additional_dependencies: [flake8-bugbear]
