# This is a Python package, but we don't use Travis's Python
# environment to build it, because of the complicated relationship it
# has with SWIG and the C++ MeCab library.  Instead we use tox,
# cibuildwheel, and a bunch of custom build scripts.
language: generic

matrix:
  include:
  - os: linux
    dist: xenial
    env: DRIVER=tox MECAB=system
  - os: linux
    dist: xenial
    env: DRIVER=tox MECAB=bundled
  - os: linux
    dist: xenial
    services: docker
    env: DRIVER=cibuildwheel MECAB=bundled
  - os: osx
    env: DRIVER=cibuildwheel MECAB=bundled

# Only run the deployment step if the build step succeeded.
# This prevents partial uploads in case the build crashed after
# building some but not all of the wheels.
script: |
  set -ex
  python3 ./scripts/travis-build.py
  python3 ./scripts/travis-deploy.py

# Deployment-related environment variables
env:
  global:
  - TWINE_USERNAME=zackw
  # TWINE_PASSWORD=[...]
  - secure: A5jpEJtU/Dv0q4gbt+VM1e2YFgJZUGUTfxXW6JjYO2wQOrDD7KRa7hYv0VxCZLD/jUcKm7x64zveGu9BEXihgZ/l4qjLcmDaQR6pnfX37aCQaX291X3mhjcfj5JrDkSbpqr2ijXW1omNFM1sE8ODlUp5Iao8BFmbBVAfopX790khhKT8IA8f9J85zi/ky3aFqHsl0SlHeGf5EIkJEusBDTom7mDP3u9siK4I1QfnVJKXS1lYWwPAaxdtYqQS+9fFY3P+9kO4Xlk5PbQqvzB3rezJTB3NvtBqlz2/KK2TMI8vFChfWZ5fOcJvXJRUTIP3hoW4d1ybdrqw74pRIMHccVbzS3ZxJw4fyW50HvwC9dNaJEWF/NexhAbCU7SFGMoth/0lMGZwLEW6bzYSYxY/WgjAawhPrYQOvuWXgDazeZkwXEvuzGbNehU++FkkdNkU2mZA38dn1q1MjcAbZs04/SvKegthL6CdSIaKUeUpEjz23itWaxrT6ShWc+U05GRXEDzxcCWXUszhCXEP9YEkUYZ391vyuY2Ydfy9UJ2xpGMJ8ngf95eDZV5dK4FZzkOdaK9FTnC2VNy75U0pauRu0LURsRiioWnQ/1u3l2PuzPAkIdUr/cAgVltZkjYhjepAYODMfNlsiSPZr5pxfN47KnFZdE0tCzERuWL3MxDgajw=
