# Generated by Django 2.2.6 on 2019-10-26 16:11

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('iam', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrincipalGroup',
            fields=[
                ('_parent', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.Group')),
                ('resource_id', models.UUIDField(db_column='resource_id', default=uuid.uuid4)),
            ],
            options={
                'db_table': 'principalgroups',
                'default_permissions': [],
            },
            bases=('auth.group',),
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
    ]
