# Generated by Django 2.2.6 on 2019-11-23 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0006_subjectrole'),
    ]

    operations = [
        migrations.CreateModel(
            name='Authorization',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=128, unique=True)),
            ],
            options={
                'db_table': 'authorizations',
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='SubjectRoleAuthorization',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('authorization', models.ForeignKey(db_column='authorization_id', on_delete=django.db.models.deletion.CASCADE, to='iam.Authorization')),
                ('role', models.ForeignKey(db_column='role_id', on_delete=django.db.models.deletion.CASCADE, to='iam.SubjectRole')),
            ],
            options={
                'db_table': 'subjectroleauthorizations',
                'default_permissions': [],
                'unique_together': {('role', 'authorization')},
            },
        ),
        migrations.AddField(
            model_name='subjectrole',
            name='authorizations',
            field=models.ManyToManyField(through='iam.SubjectRoleAuthorization', to='iam.Authorization'),
        ),
    ]
