# Generated by Django 2.2.6 on 2019-11-23 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0007_auto_20191123_1506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjectrole',
            name='authorizations',
        ),
    ]
