# Generated by Django 2.2.6 on 2019-11-23 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0008_remove_subjectrole_authorizations'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectrole',
            name='authorizations',
            field=models.ManyToManyField(to='iam.Authorization'),
        ),
    ]
