# Generated by Django 2.2.6 on 2019-11-23 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0011_auto_20191123_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectroletype',
            name='authorizations',
            field=models.ManyToManyField(db_table='subjectroletypeauthorizations', related_name='roles', to='iam.Authorization'),
        ),
    ]
