[tool.poetry]
name = "zmq_ses_communications"
version = "0.1.2"
description = "communication backend for creating a distributed system for integrating devices in a smart factory"
authors = ["Vinu Home <vinuvnair@outlook.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
pyzmq = "^18.1.1"
protobuf = "^3.11.1"
psutil = "^5.6.7"
pytest = "^5.3.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
