
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-12-27T15:37:06+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "a66744af7a70224796d20a3701baab7742448df3",
 "version": "v1.4.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
