# Generated by Django 2.2 on 2019-06-05 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_auto_20190605_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='code',
            field=models.CharField(default='wechat', max_length=50, verbose_name='code'),
            preserve_default=False,
        ),
    ]
