# Generated by Django 2.2 on 2019-06-05 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_provider_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='code'),
        ),
    ]
