# Generated by Django 2.2.3 on 2019-07-29 09:30

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_auto_20190605_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social',
            name='extra_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='extra date'),
        ),
    ]
