# Generated by Django 2.2.3 on 2019-07-30 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0006_auto_20190729_0930'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='social',
            unique_together={('provider', 'uid')},
        ),
    ]
