[tool.flit.metadata]
module = "pymcs"
# name = "pymcs"
# description = "Python Tools for MRO MCS data analysis"
description-file = "README.rst"
author = "K.-Michael Aye"
author-email = "kmichael.aye@gmail.com"
license = "BSD-3-Clause"
home-page = "https://github.com/michaelaye/pymcs"
keywords = "mars,planetary,atmosphere"
classifiers = [
    'Development Status :: 4 - Beta',
    'Intended Audience :: Developers',
    'Intended Audience :: Science/Research',
    'License :: OSI Approved :: BSD License',
    'Natural Language :: English',
    'Programming Language :: Python :: 3',
    'Programming Language :: Python :: 3.7',
    'Programming Language :: Python :: 3.8',
]
requires = [
    "pandas >=0.25",
    "tqdm >=4.41",
    "cx_Oracle >= 7.3",
]
requires-python = "~=3.7"

[build-system]
requires = ["flit_core >=2,<3"]
build-backend = "flit_core.buildapi"
