#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

install_requires = \
['python-dateutil >=2.8.0', 'pyfiglet >=0.8']

entry_points = \
{'console_scripts': ['pyconcd = pyconcd:main']}

setup(name='pyconcd',
      version='0.1.0',
      description='Countdown until the next PyCon.',
      author='Bryan W. Weber',
      author_email='bryan.w.weber@gmail.com',
      url='https://github.com/bryanwweber/pyconcd',
      py_modules=['pyconcd'],
      install_requires=install_requires,
      entry_points=entry_points,
      python_requires='~=3.5',
     )
