
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-12-21T21:57:50-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "b7fb9f91ae35881c08794231c0df25544c0f91a8",
 "version": "0.2.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
