name: MovieLens 20M
homepage: http://grouplens.org/datasets/movielens/20m/
description: |
  Stable benchmark dataset. 20 million ratings and 465,000 tag applications 
  applied to 27,000 movies by 138,000 users. Includes tag genome data with 
  12 million relevance scores across 1,100 tags. 
date: 2016-10
tasks:
  - Recommendation
  - Collaborative Filtering

download:
  handler: /archive:Zip
  url: http://files.grouplens.org/datasets/movielens/ml-20m.zip
  size: 190M
  checksum: cd245b17a1ae2cc31bb14903e1204af3
...
---
id: tmdb
description: TMDB (The Movie database) download for MovieLens movies
download:
  handler: tmdb:MovieLens