---
  - name: Avocado-VT bootstrap
    shell: avocado vt-bootstrap --yes-to-all --vt-skip-verify-download-assets
  - name: Avocado-VT test available
    shell: avocado list boot
    changed_when: false
  - name: Avocado-VT dry-run execution
    shell: avocado run --dry-run -- boot
    changed_when: false
