image: python:3.7

stages:
  - test

before_script:
  - python --version
  - pip install flake8

flake8:
  stage: test
  script:
    - flake8 setup.py
    - flake8 sr2t/sr2t.py
    - flake8 sr2t/parsers/*.py
