
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "cf6fbcd987bd9f90d240b879d845b7f761ebc1b3",
 "version": "v1.3.0.6.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
