[tool.poetry]
name = "flask-lab"
version = "0.0.2"
description = "Django-admin for flask with restful API."
authors = ["Yifei Kong <kongyifei@gmail.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/yifeikong/flask-lab"
repository = "https://github.com/yifeikong/flask-lab"

[tool.poetry.dependencies]
python = "^3.6"
peewee = "^3.13"  # peewee <= 3.12 has a bug with django-style filters
flask = "^1.1.1"

[tool.poetry.dev-dependencies]
black = "^19.10b0"
isort = "^4.3.21"
ipdb = "^0.12.3"

[tool.poetry.scripts]
flask-lab = 'flask_lab:main'

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
