# coding: utf-8

"""
    Octopus Server API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2019.6.7+Branch.tags-2019.6.7.Sha.aa18dc6809953218c66f57eff7d26481d9b23d6a
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import octopus_deploy_swagger_client
from octopus_deploy_client.events_api import EventsApi  # noqa: E501
from octopus_deploy_swagger_client.rest import ApiException


class TestEventsApi(unittest.TestCase):
    """EventsApi unit test stubs"""

    def setUp(self):
        self.api = octopus_deploy_client.events_api.EventsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_custom_query_response_descriptor_octopus_server_web_api_actions_list_event_agents_responder(self):
        """Test case for custom_query_response_descriptor_octopus_server_web_api_actions_list_event_agents_responder

        """
        pass

    def test_custom_query_response_descriptor_octopus_server_web_api_actions_list_event_agents_responder_spaces(self):
        """Test case for custom_query_response_descriptor_octopus_server_web_api_actions_list_event_agents_responder_spaces

        """
        pass

    def test_custom_query_response_descriptor_octopus_server_web_api_actions_list_event_categories_responder(self):
        """Test case for custom_query_response_descriptor_octopus_server_web_api_actions_list_event_categories_responder

        """
        pass

    def test_custom_query_response_descriptor_octopus_server_web_api_actions_list_event_categories_responder_spaces(self):
        """Test case for custom_query_response_descriptor_octopus_server_web_api_actions_list_event_categories_responder_spaces

        """
        pass

    def test_custom_query_response_descriptor_octopus_server_web_api_actions_list_event_document_types_responder(self):
        """Test case for custom_query_response_descriptor_octopus_server_web_api_actions_list_event_document_types_responder

        """
        pass

    def test_custom_query_response_descriptor_octopus_server_web_api_actions_list_event_document_types_responder_spaces(self):
        """Test case for custom_query_response_descriptor_octopus_server_web_api_actions_list_event_document_types_responder_spaces

        """
        pass

    def test_custom_query_response_descriptor_octopus_server_web_api_actions_list_event_groups_responder(self):
        """Test case for custom_query_response_descriptor_octopus_server_web_api_actions_list_event_groups_responder

        """
        pass

    def test_custom_query_response_descriptor_octopus_server_web_api_actions_list_event_groups_responder_spaces(self):
        """Test case for custom_query_response_descriptor_octopus_server_web_api_actions_list_event_groups_responder_spaces

        """
        pass

    def test_custom_query_response_descriptor_octopus_server_web_api_actions_list_events_responder(self):
        """Test case for custom_query_response_descriptor_octopus_server_web_api_actions_list_events_responder

        """
        pass

    def test_custom_query_response_descriptor_octopus_server_web_api_actions_list_events_responder_spaces(self):
        """Test case for custom_query_response_descriptor_octopus_server_web_api_actions_list_events_responder_spaces

        """
        pass

    def test_load_response_descriptor_events_event_event_resource(self):
        """Test case for load_response_descriptor_events_event_event_resource

        Get a EventResource by ID  # noqa: E501
        """
        pass

    def test_load_response_descriptor_events_event_event_resource_spaces(self):
        """Test case for load_response_descriptor_events_event_event_resource_spaces

        Get a EventResource by ID  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
