# coding: utf-8

"""
    Octopus Server API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2019.6.7+Branch.tags-2019.6.7.Sha.aa18dc6809953218c66f57eff7d26481d9b23d6a
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import octopus_deploy_swagger_client
from octopus_deploy_client.library_variable_sets_api import LibraryVariableSetsApi  # noqa: E501
from octopus_deploy_swagger_client.rest import ApiException


class TestLibraryVariableSetsApi(unittest.TestCase):
    """LibraryVariableSetsApi unit test stubs"""

    def setUp(self):
        self.api = octopus_deploy_client.library_variable_sets_api.LibraryVariableSetsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_response_descriptor_variables_library_variable_set_library_variable_set_resource(self):
        """Test case for create_response_descriptor_variables_library_variable_set_library_variable_set_resource

        Create a LibraryVariableSetResource  # noqa: E501
        """
        pass

    def test_create_response_descriptor_variables_library_variable_set_library_variable_set_resource_spaces(self):
        """Test case for create_response_descriptor_variables_library_variable_set_library_variable_set_resource_spaces

        Create a LibraryVariableSetResource  # noqa: E501
        """
        pass

    def test_custom_action_response_descriptor_octopus_server_web_api_actions_library_variable_set_usage_list_action(self):
        """Test case for custom_action_response_descriptor_octopus_server_web_api_actions_library_variable_set_usage_list_action

        """
        pass

    def test_custom_action_response_descriptor_octopus_server_web_api_actions_library_variable_set_usage_list_action_spaces(self):
        """Test case for custom_action_response_descriptor_octopus_server_web_api_actions_library_variable_set_usage_list_action_spaces

        """
        pass

    def test_delete_on_background_response_descriptor_variables_library_variable_set_library_variable_set_resource(self):
        """Test case for delete_on_background_response_descriptor_variables_library_variable_set_library_variable_set_resource

        Delete a LibraryVariableSetResource by ID  # noqa: E501
        """
        pass

    def test_delete_on_background_response_descriptor_variables_library_variable_set_library_variable_set_resource_spaces(self):
        """Test case for delete_on_background_response_descriptor_variables_library_variable_set_library_variable_set_resource_spaces

        Delete a LibraryVariableSetResource by ID  # noqa: E501
        """
        pass

    def test_index_response_descriptor_variables_library_variable_set_library_variable_set_resource(self):
        """Test case for index_response_descriptor_variables_library_variable_set_library_variable_set_resource

        Get a list of LibraryVariableSetResources  # noqa: E501
        """
        pass

    def test_index_response_descriptor_variables_library_variable_set_library_variable_set_resource_spaces(self):
        """Test case for index_response_descriptor_variables_library_variable_set_library_variable_set_resource_spaces

        Get a list of LibraryVariableSetResources  # noqa: E501
        """
        pass

    def test_list_all_response_descriptor_variables_library_variable_set_library_variable_set_resource(self):
        """Test case for list_all_response_descriptor_variables_library_variable_set_library_variable_set_resource

        Get a list of LibraryVariableSetResources  # noqa: E501
        """
        pass

    def test_list_all_response_descriptor_variables_library_variable_set_library_variable_set_resource_spaces(self):
        """Test case for list_all_response_descriptor_variables_library_variable_set_library_variable_set_resource_spaces

        Get a list of LibraryVariableSetResources  # noqa: E501
        """
        pass

    def test_load_response_descriptor_variables_library_variable_set_library_variable_set_resource(self):
        """Test case for load_response_descriptor_variables_library_variable_set_library_variable_set_resource

        Get a LibraryVariableSetResource by ID  # noqa: E501
        """
        pass

    def test_load_response_descriptor_variables_library_variable_set_library_variable_set_resource_spaces(self):
        """Test case for load_response_descriptor_variables_library_variable_set_library_variable_set_resource_spaces

        Get a LibraryVariableSetResource by ID  # noqa: E501
        """
        pass

    def test_modify_response_descriptor_variables_library_variable_set_library_variable_set_resource(self):
        """Test case for modify_response_descriptor_variables_library_variable_set_library_variable_set_resource

        Modify a LibraryVariableSetResource by ID  # noqa: E501
        """
        pass

    def test_modify_response_descriptor_variables_library_variable_set_library_variable_set_resource_spaces(self):
        """Test case for modify_response_descriptor_variables_library_variable_set_library_variable_set_resource_spaces

        Modify a LibraryVariableSetResource by ID  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
