
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-12-18T13:05:06-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "e420eb4b6213c00c1ba81f49c1b598626ed5af20",
 "version": "1.45.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
