# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-07 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailhub', '0002_auto_20180531_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='subject',
            field=models.TextField(verbose_name='Subject'),
        ),
    ]
