# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-06 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailhub', '0003_auto_20181107_0744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailrecipient',
            name='type',
            field=models.CharField(choices=[('to', 'To'), ('cc', 'C.C.'), ('bcc', 'B.C.C.'), ('reply-to', 'Reply-To')], default='to', max_length=10, verbose_name='Recipient type'),
        ),
    ]
