dist: xenial
language: python

matrix:
  include:
    - python: 2.7
      env: TOXENV=py27
    - python: 3.4
      env: TOXENV=py34
    - python: 3.5
      env: TOXENV=py35
    - python: 3.6
      env: TOXENV=py36
    - python: 3.7
      env: TOXENV=py37
    - env: TOXENV=docs

install:
   - pip install tox

script:
   - tox

deploy:
   - provider: pypi
     user: $PYPI_USERNAME
     password: $PYPI_PASSWORD
     on:
        tags: true
        distributions: sdist

notifications:
   email: false
