
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-12-30T16:58:57-0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "1edd164931144b6583811e1e2f573e86934a6f7f",
 "version": "0.1.0a1.post6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
