[tool.poetry]
name = "betterconf"
version = "1.0.1"
description = "Python configs for humans. Using OS environment."
authors = ["prostomarkeloff"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.1"

[tool.poetry.dev-dependencies]
black = "^19.10b0"
pre-commit = "^1.20.0"
mypy = "^0.761"
pytest = "^5.3.2"

[build-system]
requires = ["poetry>=1.0.0"]
build-backend = "poetry.masonry.api"
