# Generated by Django 2.2.5 on 2019-09-23 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0008_auto_20190827_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='name',
            field=models.CharField(choices=[('wxa', 'wxa'), ('wechat', 'wechat open'), ('qq', 'qq open'), ('doyin', 'doyin')], max_length=200, verbose_name='name'),
        ),
    ]
