# Generated by Django 2.2.5 on 2019-10-21 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0010_auto_20190926_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='name',
            field=models.CharField(choices=[('wxa', 'wxa'), ('wxb', 'wechat web'), ('wechat', 'wechat open'), ('qq', 'qq open'), ('douyin', 'douyin')], max_length=200, verbose_name='name'),
        ),
    ]
