[tool.poetry]
name = "carloscar"
version = "0.0.5"
description = "carloscar cli – a command line interface for productivity and every-day tasks"
authors = ["Carl Oscar Aaro <hello@carloscar.com>"]
homepage = "https://github.com/kalaspuff/carloscar-cli"
repository = "https://github.com/kalaspuff/carloscar-cli"
keywords = ["carloscar", "co", "cli", "carl oscar", "carloscar-cli"]
readme = "README.md"
license = "MIT"
classifiers = [
    "Development Status :: 1 - Planning",
    "Topic :: Software Development",
    "Topic :: Software Development :: Build Tools",
    "Topic :: Software Development :: Code Generators",
    "Topic :: Software Development :: Testing",
    "Topic :: System :: Systems Administration",
    "Topic :: Utilities",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Typing :: Typed",
    "License :: OSI Approved :: MIT License"
]

[tool.poetry.dependencies]
python = "^3.7 || ^3.8"

[tool.poetry.dev-dependencies]
flake8 = "^3.7.9"
flake8-black = "^0.1.1"
pytest = "^5.3.0"
pytest-cov = "^2.7"
black = "=19.10b0"
mypy = "^0.740.0"
codecov = "^2.0.15"

[tool.black]
line-length = 120
target_version = ["py37"]
