# This file was automatically generated by sub\epyqlib\epyqlib\cli\generateversion.py
__version_build_time__ = '2019-12-19T17:54:11.233422'

__version__ = '2019.12.4'
__sha__ = '1b6edc8bb95060cc1203772c17c650f222b3847f'
__revision__ = '1b6edc8bb95060cc1203772c17c650f222b3847f'
