# coding: utf-8

"""
    KountRISSwaggerV02

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import kount_client
from kount_client.models.billing_address_with_premise import BillingAddressWithPremise  # noqa: E501
from kount_client.rest import ApiException


class TestBillingAddressWithPremise(unittest.TestCase):
    """BillingAddressWithPremise unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBillingAddressWithPremise(self):
        """Test BillingAddressWithPremise"""
        # FIXME: construct object with mandatory attributes with example values
        # model = kount_client.models.billing_address_with_premise.BillingAddressWithPremise()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
