dist: xenial
language: python
cache: pip

matrix:
  include:
    - python: "2.7"
      env: TOXENV=py27
    - python: "3.5"
      env: TOXENV=py35
    - python: "3.6"
      env: TOXENV=py36

install:
  - pip install -U tox coveralls

script:
  - tox

after_success:
  - coveralls
