
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-12-17T15:21:31-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "4a29da00eed0016eee6bdf443a73a498bde4b882",
 "version": "1.16.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
