
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-12-31T12:41:37-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "9dc3d1011d8b6d044e0e66e4112ed1e4c4944d67",
 "version": "0.4.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
