#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

install_requires = \
['boto3']

extras_require = \
{":python_version == '2.7'": ['typing'],
 'test': ['pytest', 'pytest-cov', 'pytest-mock']}

setup(name='ecs-task',
      version='0.3.0',
      description='Helper for registering new task definitions on AWS ECS and updating associated services.',
      author='Peter Baumgartner',
      author_email='pete@lincolnloop.com',
      url='https://github.com/lincolnloop/ecs-task',
      py_modules=['ecs_task'],
      install_requires=install_requires,
      extras_require=extras_require,
     )
