
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-12-25T15:37:36-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "80b76aae70ba7f8bd186631dcb536098acd2938a",
 "version": "0.10.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
