
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-01-06T22:52:00-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "55a8a8a1ff210cf2a0eb1d83342fca0f471cc240",
 "version": "0+untagged.677.g55a8a8a"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
