[tool.poetry]
name = "pybtex-author-year-label"
version = "1.0.0"
description = "Defines an author-year inline citation style for Pybtex."
authors = ["Johan Vergeer <johanvergeer@gmail.com>"]
license = "MIT"
readme = "README.md"
keywords = ["pybtex", "labels"]
repository = "https://github.com/johanvergeer/pybtex-author-year-label"
packages = [
    { include = "pybtex_author_year_label" },
]

classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Environment :: Console",
    "Intended Audience :: End Users/Desktop",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Topic :: Internet :: WWW/HTTP",
    "Topic :: Software Development :: Libraries :: Python Modules",
]

[tool.poetry.urls]
"Source" = "https://github.com/johanvergeer/pybtex-author-year-label"
"Tracker" = "https://github.com/johanvergeer/pybtex-author-year-label/issues"

[tool.poetry.dependencies]
python = "^3.6"
pelican = "^4.2"
markdown = {version = "^3.1.1",optional = true}
pybtex = "^0.22.2"
pytest-mock = "^1.13.0"

[tool.poetry.dev-dependencies]
black = {version = "^19.10b0",allow-prereleases = true}
flake8 = "^3.7"
flake8-black = "^0.1.0"
invoke = "^1.3"
isort = "^4.3"
pytest = "^5.0"
pytest-cov = "^2.7"
pytest-pythonpath = "^0.7.3"
pytest-sugar = "^0.9.2"

[tool.isort]
# Maintain compatibility with Black
combine_as_imports = true
force_grid_wrap = 0
include_trailing_comma = true
line_length = 88
multi_line_output = 3

# Sort imports within their section independent of the import type
force_sort_within_sections = true

[tool.poetry.plugins."pybtex.style.labels"]
"author_year_1" = "pybtex_author_year_label:LabelStyle1"
"author_year_2" = "pybtex_author_year_label:LabelStyle2"

[build-system]
requires = ["poetry>=1.0"]
build-backend = "poetry.masonry.api"
