dist: xenial
language: python
install:
- pip install --upgrade pip wheel setuptools
- pip install tox
script:
- tox
matrix:
  include:
  - python: '3.7'
    env: TOXENV=py3.7-django2.2
  - python: '3.7'
    env: TOXENV=py3.7-django3.0

  - python: '3.8'
    env: TOXENV=py3.8-django2.2
  - python: '3.8'
    env: TOXENV=py3.8-django3.0
