Publish on PyPI:
  stage: deploy
  only:
    - tags
  image: python:3.8
  tags:
    - dbnomics-fetcher-toolbox
  before_script:
    - pip install twine
    - python setup.py sdist bdist_wheel
  variables:
    TWINE_USERNAME: cbenz
    # TWINE_PASSWORD: # Secret variable, see project CI settings.
  script:
    - twine upload dist/*
  environment:
    name: PyPI
    url: https://pypi.org/project/dbnomics-fetcher-toolbox/$CI_COMMIT_TAG
