[tool.poetry]
name = "poetry-template"
version = "0.1.1"
description = ""
authors = ["Mislav Jaksic <jaksicmislav@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
pytest-cov = "^2.8.1"
black = "^19.10b0"
requests = "^2.22.0"
sphinx = "^2.3.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
