# Generated by Django 2.2.6 on 2019-12-21 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0005_auto_20191221_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='retail_fee',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=15, null=True, verbose_name='Retail fee'),
        ),
    ]
