[tool.poetry]
name = "open_review_abstract_bot"
version = "0.2.1"
description = ""
authors = ["Stelios Tymvios <solliet@protonmail.com>"]
license = "BSD-3-Clause"

[tool.poetry.dependencies]
python = "^3.7"
toml = "^0.10.0"
attr = "^0.3.1"
requests = "^2.22.0"
html2text = "^2019.9.26"
praw = "^6.4.0"
beautifulsoup4 = "^4.8.2"
attrs = "^19.3.0"

[tool.poetry.dev-dependencies]

[tool.poetry.scripts]
openreviewbot = 'open_review_abstract_bot.console:run'
[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

