
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-11-05T14:30:37-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "4332e03e544ce96fed3be9ff34fd9ccd271f61df",
 "version": "0.2.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
