[tool.poetry]
name = "aftool"
version = "0.0.1"
description = "Asdil Fibrizo's tool"
authors = ["Asdil Fibrizo <jpl4job@126.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/Asdil/aftool"
repository = "https://github.com/Asdil/aftool"

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
