
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-12-18T11:25:49-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "30227b84ab7af46b01c1a975b554cb5aec0b99be",
 "version": "0.7.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
