# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-29 09:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bee_django_social_feed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedcomment',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
