# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-06-26 03:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bee_django_social_feed', '0003_auto_20180617_1053'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='feeds/%Y/%m/%d', verbose_name='\u56fe\u7247')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bee_django_social_feed.Feed', verbose_name='\u65e5\u5fd7')),
            ],
        ),
    ]
