# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-02 03:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bee_django_social_feed', '0007_auto_20180702_0732'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
