# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-04 12:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bee_django_social_feed', '0008_album_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='feed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bee_django_social_feed.Feed'),
        ),
    ]
