# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-08 01:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bee_django_social_feed', '0009_album_feed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='feed',
        ),
        migrations.AddField(
            model_name='feed',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bee_django_social_feed.Album'),
        ),
    ]
