# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-01-26 00:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bee_django_social_feed', '0016_auto_20190117_0906'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedcomment',
            name='to_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
