# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-04-01 09:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bee_django_social_feed', '0018_feed_type_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
