[tool.poetry]
name = "synodic-tools"
version = "0.1.0"
description = " A Python library to provide tooling support for the majority of Synodic software."

license = "MIT"

authors = [
    "Synodic Software"
]

readme = "README.md"

repository = "https://github.com/Synodic-Software/Synodic-Tools"
homepage = "https://github.com/Synodic-Software/Synodic-Tools"

packages = [
    { include = "synodic_tools", from = "Package" }
]


[tool.poetry.dependencies]
python  = "^3.8"
click = "^7.0"
synodic-poetry = "^0.1"
semantic_version = "^2.8.2"
gitpython = "^3.0.3"

[tool.poetry.dev-dependencies]
flake8 = "^3.7.9"
pytest = "^5.3.2"
coverage = "^5.0"
path = "^13.1.0"
black = {version = "^19.10b0", allow-prereleases = true}
sphinx = "^2.2.0"

[tool.poetry.scripts]
synodic = "synodic_tools.app:entrypoint"


[build-system]
requires        = ["poetry>=1.0"]
build-backend   = "poetry.masonry.api"
