# Generated by Django 2.2 on 2019-06-05 11:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_log_extra'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='log',
            options={'ordering': ['-created'], 'verbose_name': 'log', 'verbose_name_plural': 'log'},
        ),
        migrations.AlterField(
            model_name='log',
            name='action',
            field=models.CharField(choices=[('recharge', 'recharge'), ('shoping', 'shoping')], default='recharge', max_length=50, verbose_name='action'),
        ),
        migrations.AlterField(
            model_name='log',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='amount'),
        ),
        migrations.AlterField(
            model_name='log',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='log',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='log',
            name='error_msg',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='error message'),
        ),
        migrations.AlterField(
            model_name='log',
            name='extra',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='extra'),
        ),
        migrations.AlterField(
            model_name='log',
            name='is_success',
            field=models.BooleanField(default=False, verbose_name='is success'),
        ),
        migrations.AlterField(
            model_name='log',
            name='method',
            field=models.CharField(choices=[('wechat', 'wechat'), ('alipay', 'alipay')], default='wechat', max_length=50, verbose_name='method'),
        ),
        migrations.AlterField(
            model_name='log',
            name='number',
            field=models.CharField(max_length=50, unique=True, verbose_name='number'),
        ),
        migrations.AlterField(
            model_name='log',
            name='openid',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='openid'),
        ),
        migrations.AlterField(
            model_name='log',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='updated'),
        ),
        migrations.AlterField(
            model_name='log',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pay_log', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
