# Generated by Django 2.2.5 on 2019-11-26 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_auto_20190801_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='method',
            field=models.CharField(choices=[('douyin', 'douyin'), ('wechat', 'wechat'), ('alipay', 'alipay')], default='wechat', max_length=50, verbose_name='method'),
        ),
    ]
