# Generated by Django 3.0 on 2019-12-06 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_auto_20191126_1505'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='log',
            options={'ordering': ['-created'], 'verbose_name': 'payment log', 'verbose_name_plural': 'payment log'},
        ),
    ]
