# Generated by Django 3.0 on 2019-12-25 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0009_auto_20191206_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='action',
            field=models.CharField(choices=[('recharge', 'recharge'), ('shopping', 'shopping')], default='recharge', max_length=50, verbose_name='action'),
        ),
    ]
