[tool.poetry]
name = "dirs"
version = "0.1.0"
description = "A small library for obtaining platform dependent directory paths for application and user directories"
authors = ["Isabella Muerte <63051+slurps-mad-rips@users.noreply.github.com>"]
license = "MIT"
keywords = ["application", "directory", "xdg", ]
classifiers = [
  "Environment :: Console",
  "Intended Audience :: Developers",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.7",
  "Programming Language :: Python :: Implementation :: CPython",
  "Topic :: Software Development :: Libraries :: Python Modules",
  "Topic :: System :: Filesystems",
  "Typing :: Typed",
]

[tool.black]
line-length = 100

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
black = { version = "^19.3b0", allow-prereleases = true }
pytest-runner = "^5.1"
pytest-cov = "^2.7"
pytest = "^3.0"
codecov = "^2.0"
flake8 = "^3.7"


[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
