
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-12-22T16:11:22+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "b99a53120087e403690159efdbafa903259d5eb4",
 "version": "2019.12.22.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
