language: python
group: travis_latest
language: python
python:
  - 2.7
  - 3.6
  - 3.7
  - 3.8
  - pypy
  - pypy3
env:
    global:
        - PYTHONHASHSEED=random
        - PIP_UPGRADE_STRATEGY=eager
script:
  - pylint nti.traversal
  - coverage run -m zope.testrunner --test-path=src
after_success:
  - coveralls
notifications:
  email: dev-regression-tests@nextthought.com

install:
  - pip install -U pip
  - pip install -U setuptools
  - pip install -U coveralls coverage pylint
  - pip install -U -e ".[test]"


cache:
  pip: true

before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log
