[tool.poetry]
name = "ReCAP-Argument-Graph"
version = "0.1.10"
description = ""
authors = ["Mirko Lenz <info@mirko-lenz.de>"]

[tool.poetry.dependencies]
python = "^3.7"
networkx = "^2.4"
pendulum = "^2.0"
graphviz = "^0.13.2"
lxml = "^4.4.2"

[tool.poetry.dev-dependencies]
pytest = "^3.0"
black = {version = "^18.3-alpha.0", allow-prereleases = true}
pytest-datadir = "^1.3.1"
deepdiff = {extras = ["murmur"], version = "^4.0.9"}

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
