
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-12-30T11:33:09+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "2a0636c42860b9b7043d392ff05e0afd54ae02f4",
 "version": "0.10.14.post.dev15"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
