# Generated by Django 3.0.1 on 2019-12-21 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.FloatField()),
                ('currency', models.IntegerField(choices=[(0, 'DM'), (1, 'EUR'), (2, 'USD')], default=1)),
                ('purpose', models.CharField(blank=True, default='', max_length=128)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.Account')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='institute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.Institute'),
        ),
    ]
