
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-12-22T21:10:54+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "e0ab086600b907e1d5d4eb3a4e91809e0bd99ae4",
 "version": "0.10.13.post.dev68"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
