
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-12-26T23:13:01+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "280bff56a9fd7d73c7a05ccd8a43e7d077bf8280",
 "version": "0.3.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
