
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-11-17T22:53:51+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "6c095ee664b7574db9b87a9859ad6d8a8f18dd3e",
 "version": "v0.6.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
