# coding: utf-8

"""
    Octopus Server API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2019.6.7+Branch.tags-2019.6.7.Sha.aa18dc6809953218c66f57eff7d26481d9b23d6a
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import octopus_deploy_swagger_client
from octopus_deploy_swagger_client.models.proxy_resource import ProxyResource  # noqa: E501
from octopus_deploy_swagger_client.rest import ApiException


class TestProxyResource(unittest.TestCase):
    """ProxyResource unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProxyResource(self):
        """Test ProxyResource"""
        # FIXME: construct object with mandatory attributes with example values
        # model = octopus_deploy_swagger_client.models.proxy_resource.ProxyResource()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
