# coding: utf-8

"""
    Octopus Server API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2019.6.7+Branch.tags-2019.6.7.Sha.aa18dc6809953218c66f57eff7d26481d9b23d6a
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import octopus_deploy_swagger_client
from octopus_deploy_client.tenants_api import TenantsApi  # noqa: E501
from octopus_deploy_swagger_client.rest import ApiException


class TestTenantsApi(unittest.TestCase):
    """TenantsApi unit test stubs"""

    def setUp(self):
        self.api = octopus_deploy_client.tenants_api.TenantsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_response_descriptor_tenants_tenant_tenant_resource(self):
        """Test case for create_response_descriptor_tenants_tenant_tenant_resource

        Create a TenantResource  # noqa: E501
        """
        pass

    def test_create_response_descriptor_tenants_tenant_tenant_resource_spaces(self):
        """Test case for create_response_descriptor_tenants_tenant_tenant_resource_spaces

        Create a TenantResource  # noqa: E501
        """
        pass

    def test_custom_action_response_descriptor_octopus_server_web_api_actions_tenant_logo_get_responder(self):
        """Test case for custom_action_response_descriptor_octopus_server_web_api_actions_tenant_logo_get_responder

        """
        pass

    def test_custom_action_response_descriptor_octopus_server_web_api_actions_tenant_logo_get_responder_spaces(self):
        """Test case for custom_action_response_descriptor_octopus_server_web_api_actions_tenant_logo_get_responder_spaces

        """
        pass

    def test_custom_action_response_descriptor_octopus_server_web_api_actions_tenant_logo_put_responder(self):
        """Test case for custom_action_response_descriptor_octopus_server_web_api_actions_tenant_logo_put_responder

        """
        pass

    def test_custom_action_response_descriptor_octopus_server_web_api_actions_tenant_logo_put_responder_0(self):
        """Test case for custom_action_response_descriptor_octopus_server_web_api_actions_tenant_logo_put_responder_0

        """
        pass

    def test_custom_action_response_descriptor_octopus_server_web_api_actions_tenant_logo_put_responder_spaces(self):
        """Test case for custom_action_response_descriptor_octopus_server_web_api_actions_tenant_logo_put_responder_spaces

        """
        pass

    def test_custom_action_response_descriptor_octopus_server_web_api_actions_tenant_logo_put_responder_spaces_0(self):
        """Test case for custom_action_response_descriptor_octopus_server_web_api_actions_tenant_logo_put_responder_spaces_0

        """
        pass

    def test_custom_action_response_descriptor_octopus_server_web_api_actions_tenant_tag_test_action(self):
        """Test case for custom_action_response_descriptor_octopus_server_web_api_actions_tenant_tag_test_action

        """
        pass

    def test_custom_action_response_descriptor_octopus_server_web_api_actions_tenant_tag_test_action_spaces(self):
        """Test case for custom_action_response_descriptor_octopus_server_web_api_actions_tenant_tag_test_action_spaces

        """
        pass

    def test_custom_action_response_descriptor_octopus_server_web_api_actions_tenant_variable_set_test_action(self):
        """Test case for custom_action_response_descriptor_octopus_server_web_api_actions_tenant_variable_set_test_action

        """
        pass

    def test_custom_action_response_descriptor_octopus_server_web_api_actions_tenant_variable_set_test_action_spaces(self):
        """Test case for custom_action_response_descriptor_octopus_server_web_api_actions_tenant_variable_set_test_action_spaces

        """
        pass

    def test_custom_action_response_descriptor_octopus_server_web_api_actions_tenant_variables_get_responder(self):
        """Test case for custom_action_response_descriptor_octopus_server_web_api_actions_tenant_variables_get_responder

        """
        pass

    def test_custom_action_response_descriptor_octopus_server_web_api_actions_tenant_variables_get_responder_spaces(self):
        """Test case for custom_action_response_descriptor_octopus_server_web_api_actions_tenant_variables_get_responder_spaces

        """
        pass

    def test_custom_action_response_descriptor_octopus_server_web_api_actions_tenant_variables_missing_action(self):
        """Test case for custom_action_response_descriptor_octopus_server_web_api_actions_tenant_variables_missing_action

        """
        pass

    def test_custom_action_response_descriptor_octopus_server_web_api_actions_tenant_variables_missing_action_spaces(self):
        """Test case for custom_action_response_descriptor_octopus_server_web_api_actions_tenant_variables_missing_action_spaces

        """
        pass

    def test_custom_action_response_descriptor_octopus_server_web_api_actions_tenant_variables_put_responder(self):
        """Test case for custom_action_response_descriptor_octopus_server_web_api_actions_tenant_variables_put_responder

        """
        pass

    def test_custom_action_response_descriptor_octopus_server_web_api_actions_tenant_variables_put_responder_0(self):
        """Test case for custom_action_response_descriptor_octopus_server_web_api_actions_tenant_variables_put_responder_0

        """
        pass

    def test_custom_action_response_descriptor_octopus_server_web_api_actions_tenant_variables_put_responder_spaces(self):
        """Test case for custom_action_response_descriptor_octopus_server_web_api_actions_tenant_variables_put_responder_spaces

        """
        pass

    def test_custom_action_response_descriptor_octopus_server_web_api_actions_tenant_variables_put_responder_spaces_0(self):
        """Test case for custom_action_response_descriptor_octopus_server_web_api_actions_tenant_variables_put_responder_spaces_0

        """
        pass

    def test_custom_action_response_descriptor_octopus_server_web_api_actions_tenants_configuration_get_action(self):
        """Test case for custom_action_response_descriptor_octopus_server_web_api_actions_tenants_configuration_get_action

        """
        pass

    def test_custom_action_response_descriptor_octopus_server_web_api_actions_tenants_configuration_get_action_spaces(self):
        """Test case for custom_action_response_descriptor_octopus_server_web_api_actions_tenants_configuration_get_action_spaces

        """
        pass

    def test_delete_on_background_response_descriptor_tenants_tenant_tenant_resource(self):
        """Test case for delete_on_background_response_descriptor_tenants_tenant_tenant_resource

        Delete a TenantResource by ID  # noqa: E501
        """
        pass

    def test_delete_on_background_response_descriptor_tenants_tenant_tenant_resource_spaces(self):
        """Test case for delete_on_background_response_descriptor_tenants_tenant_tenant_resource_spaces

        Delete a TenantResource by ID  # noqa: E501
        """
        pass

    def test_index_response_descriptor_tenants_tenant_tenant_resource(self):
        """Test case for index_response_descriptor_tenants_tenant_tenant_resource

        Get a list of TenantResources  # noqa: E501
        """
        pass

    def test_index_response_descriptor_tenants_tenant_tenant_resource_spaces(self):
        """Test case for index_response_descriptor_tenants_tenant_tenant_resource_spaces

        Get a list of TenantResources  # noqa: E501
        """
        pass

    def test_list_all_response_descriptor_tenants_tenant_tenant_resource(self):
        """Test case for list_all_response_descriptor_tenants_tenant_tenant_resource

        Get a list of TenantResources  # noqa: E501
        """
        pass

    def test_list_all_response_descriptor_tenants_tenant_tenant_resource_spaces(self):
        """Test case for list_all_response_descriptor_tenants_tenant_tenant_resource_spaces

        Get a list of TenantResources  # noqa: E501
        """
        pass

    def test_load_response_descriptor_tenants_tenant_tenant_resource(self):
        """Test case for load_response_descriptor_tenants_tenant_tenant_resource

        Get a TenantResource by ID  # noqa: E501
        """
        pass

    def test_load_response_descriptor_tenants_tenant_tenant_resource_spaces(self):
        """Test case for load_response_descriptor_tenants_tenant_tenant_resource_spaces

        Get a TenantResource by ID  # noqa: E501
        """
        pass

    def test_modify_response_descriptor_tenants_tenant_tenant_resource(self):
        """Test case for modify_response_descriptor_tenants_tenant_tenant_resource

        Modify a TenantResource by ID  # noqa: E501
        """
        pass

    def test_modify_response_descriptor_tenants_tenant_tenant_resource_spaces(self):
        """Test case for modify_response_descriptor_tenants_tenant_tenant_resource_spaces

        Modify a TenantResource by ID  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
