# coding: utf-8

"""
    Octopus Server API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2019.6.7+Branch.tags-2019.6.7.Sha.aa18dc6809953218c66f57eff7d26481d9b23d6a
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import octopus_deploy_swagger_client
from octopus_deploy_client.feeds_api import FeedsApi  # noqa: E501
from octopus_deploy_swagger_client.rest import ApiException


class TestFeedsApi(unittest.TestCase):
    """FeedsApi unit test stubs"""

    def setUp(self):
        self.api = octopus_deploy_client.feeds_api.FeedsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_response_descriptor_feed_feed_feed_resource(self):
        """Test case for create_response_descriptor_feed_feed_feed_resource

        Create a FeedResource  # noqa: E501
        """
        pass

    def test_create_response_descriptor_feed_feed_feed_resource_spaces(self):
        """Test case for create_response_descriptor_feed_feed_feed_resource_spaces

        Create a FeedResource  # noqa: E501
        """
        pass

    def test_custom_action_response_descriptor_octopus_server_web_api_actions_package_search_action(self):
        """Test case for custom_action_response_descriptor_octopus_server_web_api_actions_package_search_action

        """
        pass

    def test_custom_action_response_descriptor_octopus_server_web_api_actions_package_search_action_spaces(self):
        """Test case for custom_action_response_descriptor_octopus_server_web_api_actions_package_search_action_spaces

        """
        pass

    def test_custom_action_response_descriptor_octopus_server_web_api_actions_package_version_search_action(self):
        """Test case for custom_action_response_descriptor_octopus_server_web_api_actions_package_version_search_action

        """
        pass

    def test_custom_action_response_descriptor_octopus_server_web_api_actions_package_version_search_action_spaces(self):
        """Test case for custom_action_response_descriptor_octopus_server_web_api_actions_package_version_search_action_spaces

        """
        pass

    def test_custom_action_response_descriptor_octopus_server_web_api_nu_get_built_in_feed_stats_responder(self):
        """Test case for custom_action_response_descriptor_octopus_server_web_api_nu_get_built_in_feed_stats_responder

        """
        pass

    def test_custom_action_response_descriptor_octopus_server_web_api_nu_get_built_in_feed_stats_responder_spaces(self):
        """Test case for custom_action_response_descriptor_octopus_server_web_api_nu_get_built_in_feed_stats_responder_spaces

        """
        pass

    def test_delete_on_background_response_descriptor_feed_feed_feed_resource(self):
        """Test case for delete_on_background_response_descriptor_feed_feed_feed_resource

        Delete a FeedResource by ID  # noqa: E501
        """
        pass

    def test_delete_on_background_response_descriptor_feed_feed_feed_resource_spaces(self):
        """Test case for delete_on_background_response_descriptor_feed_feed_feed_resource_spaces

        Delete a FeedResource by ID  # noqa: E501
        """
        pass

    def test_modify_response_descriptor_feed_feed_feed_resource(self):
        """Test case for modify_response_descriptor_feed_feed_feed_resource

        Modify a FeedResource by ID  # noqa: E501
        """
        pass

    def test_modify_response_descriptor_feed_feed_feed_resource_spaces(self):
        """Test case for modify_response_descriptor_feed_feed_feed_resource_spaces

        Modify a FeedResource by ID  # noqa: E501
        """
        pass

    def test_octopus_server_web_api_feeds_feed_index_descriptor(self):
        """Test case for octopus_server_web_api_feeds_feed_index_descriptor

        Get a list of FeedResources  # noqa: E501
        """
        pass

    def test_octopus_server_web_api_feeds_feed_index_descriptor_spaces(self):
        """Test case for octopus_server_web_api_feeds_feed_index_descriptor_spaces

        Get a list of FeedResources  # noqa: E501
        """
        pass

    def test_octopus_server_web_api_feeds_feed_list_descriptor(self):
        """Test case for octopus_server_web_api_feeds_feed_list_descriptor

        Get a list of FeedResources  # noqa: E501
        """
        pass

    def test_octopus_server_web_api_feeds_feed_list_descriptor_spaces(self):
        """Test case for octopus_server_web_api_feeds_feed_list_descriptor_spaces

        Get a list of FeedResources  # noqa: E501
        """
        pass

    def test_octopus_server_web_api_feeds_feed_load_response_descriptor(self):
        """Test case for octopus_server_web_api_feeds_feed_load_response_descriptor

        Get a FeedResource by ID  # noqa: E501
        """
        pass

    def test_octopus_server_web_api_feeds_feed_load_response_descriptor_spaces(self):
        """Test case for octopus_server_web_api_feeds_feed_load_response_descriptor_spaces

        Get a FeedResource by ID  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
