# coding: utf-8

"""
    Octopus Server API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2019.6.7+Branch.tags-2019.6.7.Sha.aa18dc6809953218c66f57eff7d26481d9b23d6a
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import octopus_deploy_swagger_client
from octopus_deploy_client.invitations_api import InvitationsApi  # noqa: E501
from octopus_deploy_swagger_client.rest import ApiException


class TestInvitationsApi(unittest.TestCase):
    """InvitationsApi unit test stubs"""

    def setUp(self):
        self.api = octopus_deploy_client.invitations_api.InvitationsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_response_descriptor_users_invitation_invitation_resource(self):
        """Test case for create_response_descriptor_users_invitation_invitation_resource

        Create a InvitationResource  # noqa: E501
        """
        pass

    def test_create_response_descriptor_users_invitation_invitation_resource_spaces(self):
        """Test case for create_response_descriptor_users_invitation_invitation_resource_spaces

        Create a InvitationResource  # noqa: E501
        """
        pass

    def test_load_response_descriptor_users_invitation_invitation_resource(self):
        """Test case for load_response_descriptor_users_invitation_invitation_resource

        Get a InvitationResource by ID  # noqa: E501
        """
        pass

    def test_load_response_descriptor_users_invitation_invitation_resource_spaces(self):
        """Test case for load_response_descriptor_users_invitation_invitation_resource_spaces

        Get a InvitationResource by ID  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
