# Generated by Django 3.0.1 on 2019-12-22 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gdaps', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gdapsplugin',
            options={'verbose_name': 'GDAPS plugin'},
        ),
    ]
