# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-07-11 09:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bee_django_report', '0003_report'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='report',
            table='bee_django_report',
        ),
    ]
