[tool.poetry]
name = "sipy"
version = "0.1.0"
description = ""
authors = ["Samuel Broster <sbroster@undo.io>"]

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]
pytest = "^4.6"
mypy = "^0.761"
pytest-steps = "^1.7.1"
black = "^19.10b0"
pylint = "^2.4.4"
pytest-cov = "^2.8.1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
