# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\Ui_pid_tune_methods_main_window.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(670, 300)
        MainWindow.setMinimumSize(QtCore.QSize(670, 300))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/img/Calculator-32.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QtCore.QSize(0, 0))
        self.centralwidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.gbTuneMethod = QtWidgets.QGroupBox(self.centralwidget)
        self.gbTuneMethod.setMinimumSize(QtCore.QSize(280, 0))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.gbTuneMethod.setFont(font)
        self.gbTuneMethod.setObjectName("gbTuneMethod")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.gbTuneMethod)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.gridLayoutPIDMethod = QtWidgets.QGridLayout()
        self.gridLayoutPIDMethod.setObjectName("gridLayoutPIDMethod")
        self.lblPIDType = QtWidgets.QLabel(self.gbTuneMethod)
        self.lblPIDType.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblPIDType.setFont(font)
        self.lblPIDType.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblPIDType.setObjectName("lblPIDType")
        self.gridLayoutPIDMethod.addWidget(self.lblPIDType, 3, 0, 1, 1)
        self.lblAlgorithm = QtWidgets.QLabel(self.gbTuneMethod)
        self.lblAlgorithm.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblAlgorithm.setObjectName("lblAlgorithm")
        self.gridLayoutPIDMethod.addWidget(self.lblAlgorithm, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayoutPIDMethod.addItem(spacerItem, 2, 2, 1, 1)
        self.cmbPIDType = QtWidgets.QComboBox(self.gbTuneMethod)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.cmbPIDType.setFont(font)
        self.cmbPIDType.setObjectName("cmbPIDType")
        self.gridLayoutPIDMethod.addWidget(self.cmbPIDType, 3, 1, 1, 1)
        self.cmbProccess = QtWidgets.QComboBox(self.gbTuneMethod)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.cmbProccess.setFont(font)
        self.cmbProccess.setObjectName("cmbProccess")
        self.gridLayoutPIDMethod.addWidget(self.cmbProccess, 1, 1, 1, 1)
        self.lblLambdaTauRatio = QtWidgets.QLabel(self.gbTuneMethod)
        self.lblLambdaTauRatio.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblLambdaTauRatio.setFont(font)
        self.lblLambdaTauRatio.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblLambdaTauRatio.setObjectName("lblLambdaTauRatio")
        self.gridLayoutPIDMethod.addWidget(self.lblLambdaTauRatio, 5, 0, 1, 1)
        self.lblProccess = QtWidgets.QLabel(self.gbTuneMethod)
        self.lblProccess.setMinimumSize(QtCore.QSize(105, 0))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblProccess.setFont(font)
        self.lblProccess.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblProccess.setObjectName("lblProccess")
        self.gridLayoutPIDMethod.addWidget(self.lblProccess, 1, 0, 1, 1)
        self.leLambda = QtWidgets.QLineEdit(self.gbTuneMethod)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.leLambda.setFont(font)
        self.leLambda.setReadOnly(False)
        self.leLambda.setObjectName("leLambda")
        self.gridLayoutPIDMethod.addWidget(self.leLambda, 6, 1, 1, 1)
        self.cmbTuneMethod = QtWidgets.QComboBox(self.gbTuneMethod)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.cmbTuneMethod.setFont(font)
        self.cmbTuneMethod.setObjectName("cmbTuneMethod")
        self.gridLayoutPIDMethod.addWidget(self.cmbTuneMethod, 2, 1, 1, 1)
        self.lblTuneMethod = QtWidgets.QLabel(self.gbTuneMethod)
        self.lblTuneMethod.setMinimumSize(QtCore.QSize(105, 0))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblTuneMethod.setFont(font)
        self.lblTuneMethod.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblTuneMethod.setObjectName("lblTuneMethod")
        self.gridLayoutPIDMethod.addWidget(self.lblTuneMethod, 2, 0, 1, 1)
        self.leLambdaTauRatio = QtWidgets.QLineEdit(self.gbTuneMethod)
        self.leLambdaTauRatio.setEnabled(True)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.leLambdaTauRatio.setFont(font)
        self.leLambdaTauRatio.setInputMask("")
        self.leLambdaTauRatio.setReadOnly(True)
        self.leLambdaTauRatio.setObjectName("leLambdaTauRatio")
        self.gridLayoutPIDMethod.addWidget(self.leLambdaTauRatio, 5, 1, 1, 1)
        self.lblLambda = QtWidgets.QLabel(self.gbTuneMethod)
        self.lblLambda.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblLambda.setFont(font)
        self.lblLambda.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblLambda.setObjectName("lblLambda")
        self.gridLayoutPIDMethod.addWidget(self.lblLambda, 6, 0, 1, 1)
        self.cmbAlgorithm = QtWidgets.QComboBox(self.gbTuneMethod)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.cmbAlgorithm.setFont(font)
        self.cmbAlgorithm.setObjectName("cmbAlgorithm")
        self.gridLayoutPIDMethod.addWidget(self.cmbAlgorithm, 0, 1, 1, 1)
        self.lbla = QtWidgets.QLabel(self.gbTuneMethod)
        self.lbla.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbla.setObjectName("lbla")
        self.gridLayoutPIDMethod.addWidget(self.lbla, 4, 0, 1, 1)
        self.dsba = QtWidgets.QDoubleSpinBox(self.gbTuneMethod)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.dsba.setFont(font)
        self.dsba.setDecimals(2)
        self.dsba.setMinimum(0.0)
        self.dsba.setMaximum(0.25)
        self.dsba.setSingleStep(0.01)
        self.dsba.setProperty("value", 0.2)
        self.dsba.setObjectName("dsba")
        self.gridLayoutPIDMethod.addWidget(self.dsba, 4, 1, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayoutPIDMethod)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem1)
        self.gridLayout.addWidget(self.gbTuneMethod, 0, 1, 1, 1)
        self.gbProcess = QtWidgets.QGroupBox(self.centralwidget)
        self.gbProcess.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.gbProcess.setFont(font)
        self.gbProcess.setObjectName("gbProcess")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.gbProcess)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayoutProccess = QtWidgets.QGridLayout()
        self.gridLayoutProccess.setObjectName("gridLayoutProccess")
        self.lblTc = QtWidgets.QLabel(self.gbProcess)
        self.lblTc.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblTc.setFont(font)
        self.lblTc.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblTc.setObjectName("lblTc")
        self.gridLayoutProccess.addWidget(self.lblTc, 1, 0, 1, 1)
        self.lblDeadTime = QtWidgets.QLabel(self.gbProcess)
        self.lblDeadTime.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblDeadTime.setFont(font)
        self.lblDeadTime.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblDeadTime.setObjectName("lblDeadTime")
        self.gridLayoutProccess.addWidget(self.lblDeadTime, 2, 0, 1, 1)
        self.leTc = QtWidgets.QLineEdit(self.gbProcess)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.leTc.setFont(font)
        self.leTc.setObjectName("leTc")
        self.gridLayoutProccess.addWidget(self.leTc, 1, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayoutProccess.addItem(spacerItem2, 0, 2, 1, 1)
        self.leDeadTime = QtWidgets.QLineEdit(self.gbProcess)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.leDeadTime.setFont(font)
        self.leDeadTime.setObjectName("leDeadTime")
        self.gridLayoutProccess.addWidget(self.leDeadTime, 2, 1, 1, 1)
        self.leGain = QtWidgets.QLineEdit(self.gbProcess)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.leGain.setFont(font)
        self.leGain.setObjectName("leGain")
        self.gridLayoutProccess.addWidget(self.leGain, 0, 1, 1, 1)
        self.lblGain = QtWidgets.QLabel(self.gbProcess)
        self.lblGain.setMinimumSize(QtCore.QSize(105, 0))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblGain.setFont(font)
        self.lblGain.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblGain.setObjectName("lblGain")
        self.gridLayoutProccess.addWidget(self.lblGain, 0, 0, 1, 1)
        self.lblPade = QtWidgets.QLabel(self.gbProcess)
        self.lblPade.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblPade.setObjectName("lblPade")
        self.gridLayoutProccess.addWidget(self.lblPade, 3, 0, 1, 1)
        self.sbPade = QtWidgets.QSpinBox(self.gbProcess)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.sbPade.setFont(font)
        self.sbPade.setMinimum(1)
        self.sbPade.setMaximum(16)
        self.sbPade.setObjectName("sbPade")
        self.gridLayoutProccess.addWidget(self.sbPade, 3, 1, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayoutProccess)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem3)
        self.gridLayout.addWidget(self.gbProcess, 0, 0, 1, 1)
        self.gbPIDParams = QtWidgets.QGroupBox(self.centralwidget)
        self.gbPIDParams.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.gbPIDParams.setFont(font)
        self.gbPIDParams.setObjectName("gbPIDParams")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.gbPIDParams)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayoutPIDParams = QtWidgets.QGridLayout()
        self.gridLayoutPIDParams.setObjectName("gridLayoutPIDParams")
        self.leTd = QtWidgets.QLineEdit(self.gbPIDParams)
        self.leTd.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leTd.sizePolicy().hasHeightForWidth())
        self.leTd.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.leTd.setFont(font)
        self.leTd.setReadOnly(True)
        self.leTd.setObjectName("leTd")
        self.gridLayoutPIDParams.addWidget(self.leTd, 2, 1, 1, 1)
        self.lblTd = QtWidgets.QLabel(self.gbPIDParams)
        self.lblTd.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblTd.setFont(font)
        self.lblTd.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblTd.setObjectName("lblTd")
        self.gridLayoutPIDParams.addWidget(self.lblTd, 2, 0, 1, 1)
        self.lblKc = QtWidgets.QLabel(self.gbPIDParams)
        self.lblKc.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblKc.setFont(font)
        self.lblKc.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblKc.setObjectName("lblKc")
        self.gridLayoutPIDParams.addWidget(self.lblKc, 0, 0, 1, 1)
        self.leKc = QtWidgets.QLineEdit(self.gbPIDParams)
        self.leKc.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leKc.sizePolicy().hasHeightForWidth())
        self.leKc.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.leKc.setFont(font)
        self.leKc.setReadOnly(True)
        self.leKc.setObjectName("leKc")
        self.gridLayoutPIDParams.addWidget(self.leKc, 0, 1, 1, 1)
        self.lblTi = QtWidgets.QLabel(self.gbPIDParams)
        self.lblTi.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblTi.setFont(font)
        self.lblTi.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblTi.setObjectName("lblTi")
        self.gridLayoutPIDParams.addWidget(self.lblTi, 1, 0, 1, 1)
        self.leTi = QtWidgets.QLineEdit(self.gbPIDParams)
        self.leTi.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leTi.sizePolicy().hasHeightForWidth())
        self.leTi.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.leTi.setFont(font)
        self.leTi.setReadOnly(True)
        self.leTi.setObjectName("leTi")
        self.gridLayoutPIDParams.addWidget(self.leTi, 1, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayoutPIDParams.addItem(spacerItem4, 0, 2, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayoutPIDParams)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem5)
        self.gridLayout.addWidget(self.gbPIDParams, 0, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 670, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuPlots = QtWidgets.QMenu(self.menubar)
        self.menuPlots.setObjectName("menuPlots")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.actionRefresh = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/img/cyclic-process-16.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRefresh.setIcon(icon1)
        self.actionRefresh.setObjectName("actionRefresh")
        self.actionExit = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/img/exit-16.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExit.setIcon(icon2)
        self.actionExit.setObjectName("actionExit")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/img/info-sign-16.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAbout.setIcon(icon3)
        self.actionAbout.setObjectName("actionAbout")
        self.actionHelp = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/img/help-desk-icon-16.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionHelp.setIcon(icon4)
        self.actionHelp.setObjectName("actionHelp")
        self.action_P_Step_Impulse_Response = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/img/line-graph-16.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_P_Step_Impulse_Response.setIcon(icon5)
        self.action_P_Step_Impulse_Response.setObjectName("action_P_Step_Impulse_Response")
        self.action_CL_Step_Impulse_Response = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/img/diagramm-16.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_CL_Step_Impulse_Response.setIcon(icon6)
        self.action_CL_Step_Impulse_Response.setObjectName("action_CL_Step_Impulse_Response")
        self.action_P_Bode_Response = QtWidgets.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/img/barchart-col-16.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_P_Bode_Response.setIcon(icon7)
        self.action_P_Bode_Response.setObjectName("action_P_Bode_Response")
        self.action_CL_Bode_Response = QtWidgets.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/img/barchart-bw-16.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_CL_Bode_Response.setIcon(icon8)
        self.action_CL_Bode_Response.setObjectName("action_CL_Bode_Response")
        self.menuFile.addAction(self.actionRefresh)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuHelp.addAction(self.actionHelp)
        self.menuHelp.addAction(self.actionAbout)
        self.menuPlots.addAction(self.action_P_Step_Impulse_Response)
        self.menuPlots.addAction(self.action_CL_Step_Impulse_Response)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuPlots.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.lblPIDType.setBuddy(self.cmbPIDType)
        self.lblLambdaTauRatio.setBuddy(self.leLambdaTauRatio)
        self.lblProccess.setBuddy(self.cmbProccess)
        self.lblTuneMethod.setBuddy(self.cmbTuneMethod)
        self.lblLambda.setBuddy(self.leLambda)
        self.lblTc.setBuddy(self.leTc)
        self.lblDeadTime.setBuddy(self.leDeadTime)
        self.lblGain.setBuddy(self.leGain)
        self.lblTd.setBuddy(self.leTd)
        self.lblKc.setBuddy(self.leKc)
        self.lblTi.setBuddy(self.leTi)

        self.retranslateUi(MainWindow)
        self.cmbProccess.setCurrentIndex(-1)
        self.cmbTuneMethod.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.leGain, self.leTc)
        MainWindow.setTabOrder(self.leTc, self.leDeadTime)
        MainWindow.setTabOrder(self.leDeadTime, self.cmbProccess)
        MainWindow.setTabOrder(self.cmbProccess, self.cmbTuneMethod)
        MainWindow.setTabOrder(self.cmbTuneMethod, self.cmbPIDType)
        MainWindow.setTabOrder(self.cmbPIDType, self.leLambdaTauRatio)
        MainWindow.setTabOrder(self.leLambdaTauRatio, self.leLambda)
        MainWindow.setTabOrder(self.leLambda, self.leKc)
        MainWindow.setTabOrder(self.leKc, self.leTi)
        MainWindow.setTabOrder(self.leTi, self.leTd)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "PID Tune Methods"))
        self.gbTuneMethod.setTitle(_translate("MainWindow", "2 > Tune Method"))
        self.lblPIDType.setText(_translate("MainWindow", "Type"))
        self.lblAlgorithm.setText(_translate("MainWindow", "Algorithm"))
        self.cmbPIDType.setToolTip(_translate("MainWindow", "P or PI or PID controller type"))
        self.cmbProccess.setToolTip(_translate("MainWindow", "First order with dead time or integrating"))
        self.lblLambdaTauRatio.setText(_translate("MainWindow", "Tau Ratio"))
        self.lblProccess.setText(_translate("MainWindow", "Proccess"))
        self.leLambda.setToolTip(_translate("MainWindow", "closed loop tc"))
        self.leLambda.setInputMask(_translate("MainWindow", "99.99;_"))
        self.leLambda.setText(_translate("MainWindow", "00.00"))
        self.cmbTuneMethod.setToolTip(_translate("MainWindow", "PID method"))
        self.lblTuneMethod.setText(_translate("MainWindow", "Method"))
        self.leLambdaTauRatio.setToolTip(_translate("MainWindow", "closed loop tc / process tc"))
        self.lblLambda.setText(_translate("MainWindow", "Closed Loop tc [s]"))
        self.cmbAlgorithm.setToolTip(_translate("MainWindow", "PID Algorithm"))
        self.lbla.setText(_translate("MainWindow", "a"))
        self.gbProcess.setTitle(_translate("MainWindow", "1 > Process"))
        self.lblTc.setText(_translate("MainWindow", "Time Constant [s]"))
        self.lblDeadTime.setText(_translate("MainWindow", "Dead time [s]"))
        self.leTc.setToolTip(_translate("MainWindow", "Process time constant"))
        self.leTc.setInputMask(_translate("MainWindow", "99.99;_"))
        self.leTc.setText(_translate("MainWindow", "00.00"))
        self.leDeadTime.setToolTip(_translate("MainWindow", "Process dead time"))
        self.leDeadTime.setInputMask(_translate("MainWindow", "99.99;_"))
        self.leDeadTime.setText(_translate("MainWindow", "00.00"))
        self.leGain.setToolTip(_translate("MainWindow", "Proccess gain"))
        self.leGain.setInputMask(_translate("MainWindow", "99.99;_"))
        self.leGain.setText(_translate("MainWindow", "00.00"))
        self.lblGain.setText(_translate("MainWindow", "Gain"))
        self.lblPade.setText(_translate("MainWindow", "Pade order"))
        self.gbPIDParams.setTitle(_translate("MainWindow", "3 > PID Params"))
        self.leTd.setToolTip(_translate("MainWindow", "Controller derivative time"))
        self.lblTd.setText(_translate("MainWindow", "Td"))
        self.lblKc.setText(_translate("MainWindow", "Kc"))
        self.leKc.setToolTip(_translate("MainWindow", "Controller gain"))
        self.lblTi.setText(_translate("MainWindow", "Ti"))
        self.leTi.setToolTip(_translate("MainWindow", "Controller integral time"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.menuPlots.setTitle(_translate("MainWindow", "Plots"))
        self.mainToolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionRefresh.setText(_translate("MainWindow", "Refresh"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionAbout.setText(_translate("MainWindow", "About..."))
        self.actionHelp.setText(_translate("MainWindow", "Help"))
        self.action_P_Step_Impulse_Response.setText(_translate("MainWindow", "Process Step Plot"))
        self.action_P_Step_Impulse_Response.setToolTip(_translate("MainWindow", "Process Step Plot"))
        self.action_CL_Step_Impulse_Response.setText(_translate("MainWindow", "Closed Loop Step Plot"))
        self.action_CL_Step_Impulse_Response.setIconText(_translate("MainWindow", "Closed Loop Step Plot"))
        self.action_CL_Step_Impulse_Response.setToolTip(_translate("MainWindow", "Closed Loop Step Plot"))
        self.action_P_Bode_Response.setText(_translate("MainWindow", "Bode Plot"))
        self.action_P_Bode_Response.setToolTip(_translate("MainWindow", "Proccess Bode Plot"))
        self.action_CL_Bode_Response.setText(_translate("MainWindow", "Bode Plot"))
        self.action_CL_Bode_Response.setToolTip(_translate("MainWindow", "Closed Loop Bode Plot"))
import PIDTuneMethods_rc
