
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-12-31T10:42:33+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "df1750bdb11170aa84a643ef8c4d84b3bde9c58c",
 "version": "1.1.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
