__title__ = "PyProfilers"
__description__ = "A convenient wrapper library for different Python profilers."
__url__ = "https://github.com/andreasfelix/pyprofilers"
__version__ = "0.1.3"
__author__ = "Felix Andreas"
__license__ = "GNU General Public License v3.0"
__copyright__ = "Copyright 2019 Felix Andreas"
