
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-12-24T19:44:50-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "17d3056d6d6d101a1282569cbd2797d969df5b60",
 "version": "5.0.0a10"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
