
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-12-19T15:40:45+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "302b3d51c311c29803eb48ac9dc79a393b43644b",
 "version": "0.1.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
