# Base Configuration for add extra menus into ArtellaPipe DCC Menu for Solstice

menus:
    - menu:
      - label: General
        type: menu
        children:
            - id: solstice-commands-setproject
              command: "import artellapipe; artellapipe.project.update_project()"
              type: command
              language: python
              tags: ['solstice', 'project']
              ui:
                label: "Project Setup"
                icon: 'setproject'
                is_checkable: False
                is_checked: False
                load_on_startup: False
            - id: solstice-commands-save
              command: "import artellapipe; artellapipe.project.save_scene(notify=True)"
              type: command
              language: python
              tags: ['solstice', 'save']
              ui:
                label: "Save Scene"
                icon: 'savescene'
                is_checkable: False
                is_checked: False
                load_on_startup: False
            - id: solstice-commands-lockfile
              command: "import artellapipe; artellapipe.FilesMgr().lock_file(notify=True)"
              type: command
              language: python
              tags: ['solstice', 'lock', 'file']
              ui:
                label: "Lock File"
                icon: 'lock_file'
                is_checkable: False
                is_checked: False
                load_on_startup: False
            - id: solstice-commands-unlockfile
              command: "import artellapipe; artellapipe.FilesMgr().unlock_file(notify=True)"
              type: command
              language: python
              tags: ['solstice', 'unlock', 'file']
              ui:
                label: "Unlock File"
                icon: 'unlock_file'
                is_checkable: False
                is_checked: False
                load_on_startup: False