[tool.black]
line-length = 100
exclude = '''
/(
      \.eggs
    | \.git
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
)/
| setup.py
| docs/conf.py
'''

[tool.isort]
dont_skip = "*/**/__init__.py"
known_third_party = [
    "readmemaker",
]
include_trailing_comma = true
line_length = 100
lines_after_imports = 2
multi_line_output = 3
skip_glob = [
    '*/.eggs/*',
    '*/.tox/*',
]

[tool.coverage.run]
source = ["pathvalidate"]
branch = true

[tool.coverage.report]
show_missing = true
precision = 1

# Regexes for lines to exclude from consideration
exclude_lines = [
    "except ImportError",
    "raise NotImplementedError",
    "pass",
]
