dist: trusty
sudo: false
language: python
python:
- '3.6'
cache:
  pip: true
deploy:
- provider: releases
  api_key: "$GITHUB_TOKEN"
  file_glob: true
  file: "$TRAVIS_BUILD_DIR/bundles/*"
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
- provider: pypi
  user: adafruit-travis
  on:
    tags: true
  password:
    secure: xrzl8OxwlMtumGczQDWoLtoyv1zeMUjvgPF1NwhBZQ8676PR9dyaLcnWb/RDnG2Gc7Maxq4YR5N/ycsSoxqigGVliEpltleVs3FIwAa/z0JlmtEd4AQ9N3khQaYYdgmjCOlnNkIJCS26smoB1yHP2QQVJTdY46OBnxni81jz0B2ZdMzfJJyu75qyzPonWVOSVqKaPhdqbNECwDAjdFXqY7OnwzgYCfjAcLAyXHQlOmi2+mEFDlv3cypFoxJOruxaWSm2I1mBBpwwxtlKKkpcuuQGiFuJSxKO6FPHl4SRZcTog537K63BUwVluMuw4wk4GyA/mYONNGqtxEhwkopw0B0dxxIBoH2z/K/s55iKrRzZ4G+6LeS+stfNvqzbqjdL+R98V2aZfrjqIMwAP77XIYjLpINhvCSJUmUyOROwj7C6VN0+JjsQrvglFdyQjDnIhOZJe5q83khtSjm6arDL3Fs3pYbDKSzskETHvw5S7Alj5cS9MtSojBfjgPO+CZHgTW1gQ1ON61sRKyxu78Mtem22/v+RmkQB0I/3L8LOTQEyD3EsWXeXl0W3BZrbjIf4Zg/RVnFLrhX6S2qjV5au/K3eMS3+kIjDSNENfOAF3xpe06JMrE4kO9I7GUs6mSJFZQzA01JARsDgS95R8ndSZCxjFU3hf4QdQZPSvIgJPYA=
install:
- pip install -r requirements.txt
- pip install pylint circuitpython-build-tools Sphinx sphinx-rtd-theme
- pip install --force-reinstall pylint==1.9.2
script:
- pylint adafruit_rgb_display/*.py
- ([[ ! -d "examples" ]] || pylint --disable=missing-docstring,invalid-name examples/*.py)
- circuitpython-build-bundles --filename_prefix adafruit-circuitpython-rgb-display
  --library_location .
- cd docs && sphinx-build -E -W -b html . _build/html && cd ..
